### ISSUE TITLE
The issue is about B9 part switch error 

### ISSUE THREAD

**Issue by parkerman-com** [CobaltWolf/Bluedog-Design-Bureau#1038]
it says the are more than one mariner things and similar stuff although there is one, if i dont attend it pauses the game.
Ksp log : 
[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/6080062/KSP.log)
If you could help

**Comment by zorg2044** [comment]
This is related to Kerbalism or Kopernicus as detailed here https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/977

This will be fixed in the next release. In the meantime, despite the scary phrasing, you can just click OK on the warning and continue. The actual problem is quite harmless. Some variants on some solar panels will produce slightly more EC than we originally intended, thats all.
