### ISSUE TITLE
Belle-D-4 "Nafuni" Monopropellant Engine that doesn't use Monopropellant

### ISSUE THREAD

**Issue by Bear67** [CobaltWolf/Bluedog-Design-Bureau#112]
![screenshot_14](https://cloud.githubusercontent.com/assets/5138687/17197252/c1c77dfa-5430-11e6-8f02-c4353e710409.jpg)
It'd be nice if this actually used Monopropellant.

**Comment by CobaltWolf** [comment]
other way around. I think it was supposed to have been switched but we forgot to change the name,,, @jsolson do you remember?

**Comment by jsolson** [comment]
It's supposed to be LFO, I remember the discussion. I thought I changed the title and description. It has an oddity with LFO where it does not cross feed fuel. You have to transfer manually when the internal tank runs dry. Probably fixable but I thought it was a nice "feature".

**Comment by CobaltWolf** [comment]
@jsolson there is a way to enable crossfeed

**Comment by jsolson** [comment]
I'll see what I can do.

**Comment by jsolson** [comment]
The screenshot isn't current. It's been called the Belle-D-4 "Nafuni" Secondary Engine since April.

"Secondary liquid engines for the Belle upper stage system. Attach to the gap in the truss on the Belle-D for intended use. Unintended use is not covered under warranty, but is encouraged. Includes a supply of LFO. **Note: these engines do not crossfeed and will shutdown when the internal tank runs dry. The tanks may be manually replenished using fuel transfer.**"

I'm unable to get crossfeed working without removing the internal tank. I posted a request for assistance in the forum.

**Comment by Cowboy-WY** [comment]
Just tested adding these lines in the part.cfg file and it seems to work.

PROPELLANT
		{
			name = LiquidFuel
			**resourceFlowMode = STAGE_STACK_FLOW_BALANCE**
			ratio = 0.9
			DrawGauge = True
		}
		PROPELLANT
		{
			name = Oxidizer
			**resourceFlowMode = STAGE_STACK_FLOW_BALANCE**
			ratio = 1.1
                }

**Comment by Bear67** [comment]
> The screenshot isn't current. It's been called the Belle-D-4 "Nafuni" Secondary Engine since April.
Aye, looks like I was still using 0.10. (updating to latest Pre-Release.)
Well Darn, I could have used a mono engine this early in my ksp career mode.

**Comment by CobaltWolf** [comment]
@Cowboy-WY Excellent!

@Bear67 Yipes, that was for 1.0.5 as well. Don't worry, there are surely more coming. What size in particular were you looking for? It'd also be worth paying attention to @raveloda's Probes Plus mod, as his next content update should focus on propulsion systems in vaguely the same size class.
http://forum.kerbalspaceprogram.com/index.php?/topic/131145-wip-coatl-aerospace-probesplus-dev-thread-v0131-beta-61816/#comment-2394062

**Comment by Cowboy-WY** [comment]
One thing to note is that the engine only pulls equally from other tanks until its own tank is empty.  Once its own tank is empty the engine stops regardless of other tanks still having fuel/oxidizer.

**Comment by CobaltWolf** [comment]
huh.... what if you do that AND enable crossfeed the way @jsolson has?

**Comment by Cowboy-WY** [comment]
Seems to not matter.  Since the engine part is surface mounted AND has its own fuel supply it doesn't crossfeed.  Using the resourceFlowMode = STAGE_STACK_FLOW_BALANCE makes it pull from all tanks in the stage, but it still dies when its own tank is empty.  

Not as bad as it sounds, testing with a basic Agena-D stage ( Belle-200 tank, D-35 engine, 2xD-4 engines) running all engines empties the D-4 tanks with about 9 seconds of burn time left.  A 10% increase in the D-4 tank capacity should bring it to about even.  I'll try it shortly.

**Comment by Cowboy-WY** [comment]
Looks like a 20% increase to bring them close to even since I forgot there were 2 DF-4 engines pulling from all tanks including the opposite side DF-4

Testing Data for Agena-D (Belle TRU,Belle-200 tank, D-35 engine, 2xD-4 engines)

- Normal config - LF/O 9.0/11.0 - 2943 Vac DV - DF-4 tanks empty with 9 seconds D-35 Burn time remaining
 
- +10% Config - LF/O 9.9/12.1 - 2972 Vac DV - DF-4 tanks empty with 4 seconds D-35 Burn time remaining
 
- +20% Config - LF/O 10.8/13.2 - 3000 Vac DV - D-35 tank empty with 1 second DF-4 Burn time remaining


Not sure what the goal of a change would be.  Just enabling it to get fuel from other areas or also timing the burn out of an Agena-D Stage.

**Comment by jmrd98** [comment]
It's probably of only minor interest, but i've been experimenting with that fuel flow method in other parts of the mod, specifically the mercury/atlas stack, with its intense joy of going unstable on stage separation. (NOTE: This might just be me, i'm not accusing it of being unstable.) Results have been neutral, but I haven't had a lot of testing time either. As I normally 'fixed' the flipping by disabling the top most tank until stage sep, I hoped this would help. But yea, mixed results.

The mode results in an engine drawing evenly from all tanks in a stage, not "a tank at a time, top down" style. What bugs me is i'm trying to find a downside to that, gameplay wise, for a standard booster stack. (I'm glad they added it, I had asked for such a feature long ago.) Any thoughts?

**Comment by Cowboy-WY** [comment]
I don't see a downside for standard stack type vehicles.  Only an inconvenience for specialty type vehicles that have stuff radially attached that you don't want to use.

As for the Mercury-Atlas...

The biggest reason for flips is too much speed.  At default settings it has way too much TWR for any kind of normal launch, it would only work going straight up for 25km or so to start.

I make it work pretty well by changing the thrust limits, 65 on the sustainer and 52 on the boosters.  Throw off the LES at about 250m/s and the boosters at 650m/s.  Flys pretty well on an average ascent profile to 200-250km.

**Comment by jsolson** [comment]
If it wasn't for the fact the engine will shut down when the internal tanks runs out I'd say go with the STAGE_STACK_FLOW_BALANCE method, but I think that will cause confusion.

I wonder, if we were to make it a monopropellant engine with an internal MP tank, would it have the same behavior where it shuts down when the internal tanks runs out and there is still MP elsewhere.

**Comment by Cowboy-WY** [comment]
Monopropellent acts differently than the normal fuel flow rules.  It pulls from any available tank and as long as there is any monopropellent anywhere on the vehicle it will continue to work.  Bad part is that is can use monopropellent across stages, but always seems to draw from the lowest stage in the current vehicle that has remaining monopropellent.

**Comment by CobaltWolf** [comment]
Should we just switch it back to mono like it originally was?

**Comment by jsolson** [comment]
I think we should leave it alone. As is the main engine won't draw fuel from the secondary's tank, and the secondary will only pull from it's own tank. It's an isolated system that you can manually replenish.

There are a variety of ways to setup the SPS. It's easy to roll your own with an MM patch.

**Comment by CobaltWolf** [comment]
Ok. Then the name needs to get fixed.

**Comment by jsolson** [comment]
Closing. The name is fine, the OP was using an old version.
