### ISSUE TITLE
BlueSmurff.cfg does not affect all engines

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#1131]
It contains dedicated patches and misses sevceral engines, for example the bluedog_E1

**Comment by zorg2044** [comment]
I belive JSO intends to deprecate Blue smurff and no longer officially support it in the near future.

**Comment by Gordon-Dry** [comment]
As over the years it was repeatedly said that BDB is tailored for 2.5x - 3x stock, it perfectly fits to JNSQ and this makes me curious why JNSQ is even mentioned in BlueSmurff.cfg to set that @systemScale = 2.7

**Comment by jsolson** [comment]
Yeah it's badly out of date, mainly because it's unofficially deprecated. We used to test in stock and depend on this patch to accommodate the various rescales, but nowadays we look at 2.5x as the default scale and we ignore stock. What needs to happen is deactivate it and test for impacts. I'd expect some light weight or very tight deltaV historical missions might need a mass adjustment, but other than that it should have no noticeable effect on <3x rescales.

**Comment by Gordon-Dry** [comment]
I pruned that config for now.

btw perhaps I get dementia - there is a slightly chance that I opened a PR to add JNSQ to that config last year or so...  *grin*
