### ISSUE TITLE
Deprecated part conversion

### ISSUE THREAD

**Issue by maddavo** [CobaltWolf/Bluedog-Design-Bureau#1209]
Is there a list somewhere for doing search/replace of deprecated parts?
I have a save game which throws multiple errors which boil down to the following parts:
bluedog.Saturn3125mFairingBase.PF
bluedog.Saturn.S1F.Tankage
bluedog.E1
bluedog.Apollo.Block2.RCSlinearSingle

What are the equivalent current parts?

**Comment by zorg2044** [comment]
the PF base is created by procedural fairings. If you add it back in I believe it should come back. Otherwise substitute it for the stock or SAF fairing equivalents

bluedog_FairingBase_3p125m
bluedog_FairingBase_3p125m_SAF

bluedog_E1_engine

bluedog_Saturn_S1E_Tank

bluedog_Apollo_RCS_Linear

Don't expect any of these craft to not be functionality wrecked even if they load. The S1 tanks and E1 engines are substantially different functionally and more importanty in size and node position.
