### ISSUE TITLE
BDSEP-TVO SSTV Camera can't be picked up after deployment

### ISSUE THREAD

**Issue by Echo1-1A** [CobaltWolf/Bluedog-Design-Bureau#1290]
When a Kerbal attempts to pick up the part in question after it was deployed, it would remain in place in a non-functional state, while creating a duplicate in the Kerbal's inventory. The non-functional original is no longer anchored on the surface, and can be bumped around by other things. While the duplicate can't be deployed again unless it was put inside another inventory, and then retrived.

**Comment by Rodg88** [comment]
Can you post your KSP.log? And you definitely deployed via the icon in the kerbals inv, not with Eva construction?

**Comment by Echo1-1A** [comment]
Unfortunately, I didn't preserve the log file of the run during which the issue occured. I will try and see if I can recreate the issue, and provide the log file then.
And yes, it was deployed via the Kerbal's inventory.

**Comment by Echo1-1A** [comment]
[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/9365270/KSP.log)
Not sure if this I uploaded it correctly, but here's the log file of my attempt at recreating the issue.
Something worth noting is that, unlike the first time, I could not deploy the 'duplicate' in the Kerbal's inventory, even after placing and taking it out of different containers.

**Comment by Rodg88** [comment]
Haven’t tested in game yet myself, but from the log I saw you have a fairly old version of KSPCF, might be worth trying again after updating that (and harmony) https://github.com/KSPModdingLibs/KSPCommunityFixes/releases

otherwise, was it happening on a camera that was placed before a recent update to BDB? And did newly placed ones work better? Some experiment definitions have been changed recently, and it’s possible KSP doesn’t handle that well. Another thing that may have done something (but unlikely) is trying to have two cameras connected to one central station.

**Comment by Echo1-1A** [comment]
I'll be sure to test it again after updating KSPCF. As for BDB version I'm using, it was downloaded 4 days ago, not sure if it's after the change to experiment definitions. Also, my camera was deployed after that, in fact, I opened this issue right after I've encountered the bug.

**Comment by Rodg88** [comment]
Found the issue, thanks!

**Comment by Echo1-1A** [comment]
Glad I could be of help!

**Comment by Rodg88** [comment]
@CobaltWolf this was caused by a lack of `deployAnimation`. It stops breaking if you just set `deployAnimationName` to the same animation as `activeAnimationName`, but that causes it to play the full active animation before you pack it up. A quick 'unpack' animation with no movement that can be the `deployAnimation` instead would work nicely.

**Comment by CobaltWolf** [comment]
second animation is called "deployFake"
