### ISSUE TITLE
LTV/SheLab notes

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1324]
- shelab doesn't seem to be a control point? not sure of the terminology but put in crew and KSP says no control when you launch
- LTV: there is a flag directly on top of the solar panels, that just floats if you open the panels

p.s. this thing is SLICK

**Comment by OrbitalManeuvers** [comment]
Other things I tested that worked great:
- floodlight
- robotics deployment on lunar surface
- driving
- core sample
- opening/closing panels and storage on LTV
- crane
- new fenders
- rcs fit with hinge
- actually landing from orbit, CoM seems good

**Comment by Rodg88** [comment]
I noticed the new porch needs an updated collider too

**Comment by CobaltWolf** [comment]
> * shelab doesn't seem to be a control point? not sure of the terminology but put in crew and KSP says no control when you launch
> 

It shouldn't have one, all piloting is done autonomously via the truck descent stage. Which, if I remember, is its own separate part now.

>     * LTV: there is a flag directly on top of the solar panels, that just floats if you open the panels
> 

You mean when you deploy the solars, the flagTransform stays in position instead of following the door? Damn, I thought I'd fixed that. No problem - it was just a child of the root, instead of a child of the door, so it wasn't following it. Easy enough to fix.

**Comment by OrbitalManeuvers** [comment]
Parenting looks good. UV needs a little help?

https://i.imgur.com/3Xsijn9.png

**Comment by CobaltWolf** [comment]
Uhm. Hmm. It wasn't like that before...

**Comment by OrbitalManeuvers** [comment]
*zip*
