### ISSUE TITLE
No control

### ISSUE THREAD

**Issue by Raqnick** [CobaltWolf/Bluedog-Design-Bureau#1336]
There is no antennas on probe or lander.

**Comment by Rodg88** [comment]
The craft files for voyager mars? Or the antenna parts in general? I’ll need a ksp.log to look into this.

**Comment by Raqnick** [comment]
Voyager Mars craft.Signal is 0.00 and antennas have no transmission strength.
https://mega.nz/file/QtsmBYjb#n5xXMh582Zm1Q4FcFjxICHzI2pWtAJpuV-Z4raaP68M

**Comment by Rodg88** [comment]
Firstly, not related, but about log spam causing the log to be so big, Artemis Construction Kit is much happier with both https://spacedock.info/mod/3064/Shaddy and http://taniwha.org/~bill/Shabby_v0.3.0.zip installed. it should stop spamming the log when you have those. Will probably speed up your game load too. This issue should be fixed in a future version of ACK too.

The other issue is due to the mod NCAP incorrectly patching for RemoteTech, causing all other mods to think RemoteTech is installed, breaking antennas. I've reported it on that mod's thread.
