### ISSUE TITLE
Proper Kerbalism support for AARDV, Agustus, other ORV's

### ISSUE THREAD

**Issue by rp1-lox** [CobaltWolf/Bluedog-Design-Bureau#1372]
Current resupply vehicles only present options to store water, H2/O2, ore, and MaterialsKits. If proper Food, Water, and Oxygen could be added, I would be very grateful. 

Thank you for your time!

**Comment by Rodg88** [comment]
I can add the default kerbalism tank types to cargo hauler parts, but as the BDB dev team don't use kerbalism, any fine tuning would need to be community submitted patches.

**Comment by Rodg88** [comment]
@rp1-lox You can try saving this file:
https://raw.githubusercontent.com/CobaltWolf/Bluedog-Design-Bureau/1.11-development/Gamedata/Bluedog_DB/Compatibility/Kerbalism/KerbalismCargo.cfg

And place it in GameData/Bluedog_DB/Compatibility/Kerbalism/ (the Kerbalism folder is new, you can create it yourself)

Let me know how it works out

**Comment by rp1-lox** [comment]
Throws an error - No tank type "supplies" exists.

**Comment by rp1-lox** [comment]
if HabTech is installed, it throws the error "no part ht_02 exists"

**Comment by Rodg88** [comment]
Does habtech give an error without this patch? The patch should have nothing to do with habtech.

Otherwise try replacing the first line in the patch with this:
`@PART[bluedog*,Bluedog*]:HAS[@MODULE[ModuleB9PartSwitch]:HAS[#switcherDescription[Cargo]]]:NEEDS[B9PartSwitch,KerbalismDefault]:AFTER[KerbalismDefault]`

**Comment by rp1-lox** [comment]
HabTech error is non-critical. LRTR is not compatible otherwise and is no longer under development.  I think this should be categorized as complete.

**Comment by Rodg88** [comment]
Ah yes looks like LRTR doesn’t ship the tank types that normal kerbalismconfig includes, while having the same config folder name which will be triggering the patch, causing errors aplenty I assume. If I was going to add support kerbalism it would have to be the base version, too many variables otherwise.
