### ISSUE TITLE
Error with bdbScrapMetal and NERVA_II subtypes

### ISSUE THREAD

**Issue by shiftingvoid** [CobaltWolf/Bluedog-Design-Bureau#1385]
Hello
I tried to use the mod with extraplanetary launch pad and the latest realease and it gave me a fatal error (log attached) on bdbScrpMetal and NERVA_II subtypes
[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/12182054/KSP.log)

**Comment by Rodg88** [comment]
I don't think you should have Extraplanetary Launchpads and Simple Construction in the same install  (SC ships it's own copy of EL), and having both confuses the patching system, causing this error.

The NERVA_II error is due to something else messing with the engine, possibly rational resources. I've let the dev of RR know.
