### ISSUE TITLE
Docking ports

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#140]
From Araym via pm...

Agena, MOS and Gemini docking ports lacks of
	stagingIcon = DECOUPLER_VERT
to show in the staging sequence, if activated the decoupler thru VAB menu.

--------------------------------------------

Uhm... another issue, found on the "bluedog_agenaPort", that confused me untill I noticed the node placement

it has 2 nodes on top:

- the "top" one, with the fairing module, to allow to cover the node with the "bluedog_agenaNoseCone"

- and obviously, inside the docking collar, the "dock" one needed for docking with the Gemini

BUT, as it is now, the "top" one is a fixed-joint.
If anyone put the nosecone on it, it's impossible to release, and if it is placed on the dock one, to decouple the nosecone, it does not activate the fairing (aside from clipping the docking collar).
I added a decouple module on the top one (basically the only option, because if disabled, there is no fairing and/or no flush assembly)

**Comment by Cowboy-WY** [comment]
When I try this by attaching the nose cone to the top node, the decoupler in the nosecone works  - recently fixed in #119. (Araym may be using a version prior to that fix)  So no need for decoupler on the top node of the bluedog_agenaPort, unless it is intended to be connected to something other than the nosecone and would need to decouple itself.

The use case I see for the one inside the collar is pre-connecting the gemini docking mechanism during assembly.  This would negate the upper node fairing creation, but works using the right-click menu when in flight.  

Araym is right that neither the Belle docking port, the MOL docking port nor the Leo docking mechanism can be added to the staging.  

adding "stagingIcon = DECOUPLER_VERT" to each config fixes that, but the Belle port also needs "stagingEnabled = False" under the node module.

Let me know if you would like this done.

**Comment by jsolson** [comment]
By all means, dive in!

**Comment by Araym-KSP** [comment]
[Araym is right that neither the Belle docking port, the MOL docking port nor the Leo docking mechanism can be added to the staging.

adding "stagingIcon = DECOUPLER_VERT" to each config fixes that, but the Belle port also needs "stagingEnabled = False" under the node module.]

... actually, in KSP, docking ports DOES NOT need the "stagingEnabled = False", because KSP considers them already NOT part of the staging sequence.
Adding that line make the docking port ALWAYS shown in the staging events as "decoupler".

**Comment by jsolson** [comment]
> actually, in KSP, docking ports DOES NOT need the "stagingEnabled = False", because KSP considers them already NOT part of the staging sequence.
Adding that line make the docking port ALWAYS shown in the staging events as "decoupler", without any possibility to switch between the 2 modes.

Strange but true. Yet the squad docking port does use it and does not have that behavior. Something's fishy.

This seems wrong:
> referenceAttachNode = dockingNode

There's no such node defined.

**Comment by CobaltWolf** [comment]
That's a game object in unity with the Z+ facing the other docking port. 

-----Original Message-----

**Comment by Cowboy-WY** [comment]
I don't know the right or wrong way to use these variable.  I just compare working parts to non-working parts and experiment until it works.

The MOS and Gemini Ports add and remove the staging icon as expected.  The Agena port seems to always be on the staging menu.

The MOS and Agena ports don't decouple, while the Gemini one does.

for Agena, changing referenceAttachNode = dockingNode to referenceAttachNode = dock makes it decouple

for MOS port, changing referenceAttachNode = dockingNode to referenceAttachNode = top makes it decouple

**Comment by Cowboy-WY** [comment]
A complete round of testing shows me this

stagingEnabled line under ModuleDockingNode has no effect being there or not, seems it is an old variable that is no longer used
The Agena port has a staging icon because of the ModuleJettison line.  commenting it out removes the permanent staging icon, but it is needed or the fairing

I'll change the two referenceAttachNode lines in Agena port and MOS port, then it looks like everything works as expected.  I'll remove the stagingEnabled lines to avoid confusion.

**Comment by jsolson** [comment]
So the stagingEnabled / ModuleJettison combo is giving us buggy behavior, I'll buy that.

These ports didn't decouple before... sigh, you're right. They work now. I didn't test them but glancing at the config the Apollo ports look ok.

As best I can tell, referenceAttachNode should refer to the cfg file define stack node, and nodeTransformName/controlTransformName refer to the unity objects. I'm guessing you're using the default names for these two so they don't need to be listed.

Somewhat related, the Agena nosecone has a second attach node buried up in the cone. Does this have a purpose? And it's ModuleDecouple seems a bit over powered. The thing flys off like a missile. Maybe we should tone that down.

**Comment by CobaltWolf** [comment]
It's used for this:

**Comment by Araym-KSP** [comment]
to remove the problem with the Agena docking port (always shown in the VAB-staging sequence as decoupler), personally removed the added line about the staging icon (then, it cannot be staged by "spacebar", but still, if needed, by part menu or actions)

**Comment by CobaltWolf** [comment]
So, is everything working with the ports now? Or do I need to pull them up
in Unity and add/move some transforms.

Matthew Mlodzienski
3D Animation and Visual Effects
Westphal COMAD 2017
