### ISSUE TITLE
Merge LR-87 and LR-91 variants

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#1465]

**Comment by JacobB094** [comment]
I'd like to mention one possible issue associated with it: propellant selection, particularly with hypergolic propellants patch. With the current patch, everything but Titan I hardware gets changed to AZ-50, including Titan II engine variants that are supposed to be kerolox. I don't know if a variant can change propellants, or if patching different propellants in is feasible. 

Either way, I would appreciate if during the merge, this issue was taken into account, and the AZ-50 patch properly updated, so that each engine has the propellant mix that it should have. The hypergolics patch greatly enhances the BDB experience, particularly with the Titans.

**Comment by Pappystein** [comment]
When the parts are stabilized I will look at it for the purposes of the Hypergolic BDB patch.   @JacobB094

**Comment by CobaltWolf** [comment]
I'd offer than stock LF/O behaves much more like AZ-50/NTO than it does RP-1/Oxygen. If anything you should be making something to make kerolox behave differently :)

**Comment by JacobB094** [comment]
While I wouldn't mind that, the community seems to have settled onto a convention that LFO=kerolox. Having AZ-50/NTO at all is a bold move. :) I've been considering setting up a similar patch for Benjee's mods (and Tantares, if it keeps improving, though it should properly use UDMH), but introducing a proper kerolox mix would be a job for a "total conversion" of sorts.

**Comment by Pappystein** [comment]
Mixture ratio wise LF/O in KSP is almost exactly Aerozine 50 / NTO combination.   however mass wise it is actually Kerolox.   SO it is a mish-mash of both.   Which is stupid *1000

That is why the Titan patches for example fill to 90% max volume when using the AZ50/NTO patches.   Because it is denser than Kerolox.  Ideally it should be fill to 94% but B9PartSwitching + base KSP only give us 10% increments.

Mind you this was something Jso did the calculations on and informed me of why I was having problems with my patch (there is an entire chain somewhere here in github about that.

**Comment by Pappystein** [comment]
Also @JacobB094 The LR87-AJ-5K (the Kerolox engine based on the AZ50 LR87-AJ-5) Runs as LFO in my game.   either you are using a different patch than what I developed in Pafftek or you have another patch that is overwriting it if the xK engines are not Kerolox  (sorry I didn't notice you mentioning that in your OP!)

**Comment by JacobB094** [comment]
It does seem like this issue was fixed. I'm waiting for the update so that I can finish up my RSE compatibility patch for BDB.

**Comment by Rodg88** [comment]
I commented this on the PR, but I think the engine merges are essentially done if you want to finish the RSE patch @JacobB094

**Comment by Pappystein** [comment]
@JacobB094   Sorry I misunderstood / Failed to test fully what you were saying about the Patch.  I was restructuring the patch today to make it "More Error Proof"  Due to your comments as well as the inclusion of the LH2 LR87 Twin in the conjoined engine bank.  In doing so I found the problem with the OG patch.  

Originally I made all Titan Engines  Hypergolic.   THEN I went back and added Kerolox (LF/O) back to the -K engines.

I never removed the Hypergolic fuel choice on those Kerolox engine variants.  So those engines could RUN on BOTH.  I have fixed  it (I hope) in the patch and am now working on testing it.   Hopefully both the AJ9 patch and the Hypergolic Patch will be updated latter today
