### ISSUE TITLE
Condor solar panel subtype angles

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1501]
When the Condor SSP2 solar panel is switched to 'Straight' mode it continues to only catch rays in the 'Default' setting's direction, as though the part switch isn't rotating something somewhere :) I'm brilliant.

Here's the panel catching end-on - the direction that would be correct for 'Default'
https://i.imgur.com/YXPpHa6.png

**Comment by Rodg88** [comment]
Ahh the joys of deployable solar panels

**Comment by Rodg88** [comment]
https://github.com/user-attachments/assets/822baaee-4bb2-44c9-89cb-26dd2ddc2918

Had to restructure the whole part to use a single suncatcher, involving offsetting the straight deploy mesh so it's panel is in the same position as the default panel when deployed.
![image](https://github.com/user-attachments/assets/92a7f271-ee6d-4737-9751-122990f3bff6)

I then offset and rotate the part on that subtype so the part doesn't jump around when you switch subtypes
https://github.com/user-attachments/assets/4d328b12-7a7f-4999-a48c-e3cd19647520

All because you can't edit the suncatcher in-game, or apparently switch them with mesh switches.
