### ISSUE TITLE
ckan version B9PartSwitch error message

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [CobaltWolf/Bluedog-Design-Bureau#1565]
I dont know where to put issues with the ckan version as it is not being developed by the actual devs I think, so I put it here. I was loading into my game when I got an error message from b9partswitch. I ignored it and when I loaded into my save it crashed. I will attach a photo of the error message and the log here. 
Log: **https://paste.drhack.net/?586f24bcd0ccb9e0#B9AocaeDhjPmWa7bCJhAtv7oHiagFA5exjYi3TSC8dJR**

Error Message:
![220200_566](https://github.com/user-attachments/assets/39e63ed2-641c-4852-8bba-7ace23200483)

**Comment by Rodg88** [comment]
There seem to be some installation errors/missing files somehow, so maybe a corrupt download? Can you try in CKAN uninstalling BDB, selecting the 'purge from cache' option when right clicking on the mod listing, then reinstalling? This should redownload the mod.

The CKAN version is the same btw, it even downloads from the github releases.

**Comment by mrdiamondmanguydudeman** [comment]
Okay, I'll try, thank you.

**Comment by mrdiamondmanguydudeman** [comment]
It didn't work, gave the same error message
I am using the methalox variants and community category extra thing so maybe thats the problem?
edit: nope, it wasnt the extras

**Comment by Rodg88** [comment]
Those shouldn't be an issue yeah. Can you post the modulemanager.configcache file from your gamedata too? If you view folder properties on the Bluedog_DB folder in your GameData, how big is it? It should be 2.38GB

On the off chance its still a download issue, you could try manually installing it from spacedock instead of CKAN too (spacedock should be more reliable than github to download large files from, CKAN currently links to the github one). Just delete the Bluedog_DB folder in gamedata and replace it with the one from the zip.

I don't see anything else installed in your log that would be messing with parts that much, which is why I still kinda suspect a download corruption/installation issue.

**Comment by mrdiamondmanguydudeman** [comment]
okay, great ill try

**Comment by mrdiamondmanguydudeman** [comment]
i have so many mods that the file , when pasted into what i use, literally has my browser run out of memory

**Comment by Rodg88** [comment]
should be able to zip it and then just drag it into a github post and it should upload it

**Comment by mrdiamondmanguydudeman** [comment]
oh ok

**Comment by mrdiamondmanguydudeman** [comment]
[ModuleManagerConfigCache.zip](https://github.com/user-attachments/files/17262630/ModuleManagerConfigCache.zip)
I got the file and the file size for the folder is 2.35gb

**Comment by mrdiamondmanguydudeman** [comment]
new error, when I loaded in, it just immediately crashed with the error message saying "VirtualAlloc remapping failed"

**Comment by Rodg88** [comment]
Oh are you just running out of memory? If you only have 8GB that simply may not be enough, esp with parallax on top of BDB.

Id try without parallax, and maybe clean up some drive space too

**Comment by mrdiamondmanguydudeman** [comment]
i tried without parallax but that doesnt fix the b9partswitch issue

**Comment by Rodg88** [comment]
Oh, you seem to have a 2nd copy of the mod installed inside a 2nd Gamedata. Delete that and it should work.
