### ISSUE TITLE
K-15 parts not mirroring when snapping to attachment nodes

### ISSUE THREAD

**Issue by InterstellarDrifter** [CobaltWolf/Bluedog-Design-Bureau#1580]
The new K-15 is freaking awesome, but one little issue is that parts are not mirroring. The parts that are supposed to mirror, disappear when they snap to nodes. When placed elsewhere on the fuselage, they do mirror, but not in the chiral way that is expected. Since parts have chirality, they are upside down and therefore visually wrong and possibly unusable.

**Comment by Rodg88** [comment]
It's precisely due to the mirroring issue that you can't use symmetry with the nodes, and have to place them on each side individually. For eg: build out the left wing with control surfaces on the node, then copy it and put it on the right side, and select the right side variant for all the parts of the right wing. It's just a limitation of KSP.
