### ISSUE TITLE
Apollo IVA (Volunteer needed)

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#169]
Need a dedicated Apollo IVA.

**Comment by Modsojoy** [comment]
Ayy m8, Im on it.

**Comment by Modsojoy** [comment]
Problem is - I cannot Texture. I can make Placeholders with Solid colours, Run the stuff through Unity and even make some custom Props, But i CANNOT Texture.

**Comment by Modsojoy** [comment]
![capture](https://cloud.githubusercontent.com/assets/21351692/18655989/4dfd2de2-7ebb-11e6-8a33-82e3b9cac1de.PNG)

**Comment by Modsojoy** [comment]
Screenshot of the IVA Model in Unity, Spars and Main panel visible, Smooth Shading from blender kinda Throw's it off so i might Switch back to Flat

**Comment by CobaltWolf** [comment]
closing this to open new one for all IVAs. @Modsojoy if you're still interested in Apollo, can you post on the thread, ask the user 'Daelkyr' what the status is on his CM IVA? I just realized you both started working on one and I don't want to accidentally have y'all duplicating work. :)

**Comment by Modsojoy** [comment]
Ayylmao cobalt sorry for the late response, I've been getting blasted with emails from here so i just stopped checking them, No i dont think im going to make one, I have the LEM Iva to Completely Redo and the Apollo IVA For SSTU. which unfortunately cannot be Adapted to the pod from BDB, This one got kinda lost due to the External mesh being a pain in the [Redacted][Redacted] Makes me want to shove a [Redacted] Tipped carbon pole right up its [Redacted]

**Comment by Modsojoy** [comment]
Also @Daelkyr13, Ayym8
