### ISSUE TITLE
USI-LF compatibility patch

### ISSUE THREAD

**Issue by Araym-KSP** [CobaltWolf/Bluedog-Design-Bureau#238]
- missing Apollo CM block 3
- supplies quantites, hab value (and reciclers?????) must probably adjusted looking at changelog, to support accordingly related mission per pod/crewed part:

"The default supply consumption has been adjusted slightly downward (from 16.2 per day to 10.8 per day) - no more second breakfasts. To adjust for this, change per second consumption to 0.0005 from 0.00075 in the GUI. Crew capacity only results in a 7.5 day hab bonus as opposed to 30 days."

**Comment by jmrd98** [comment]
I wrote them, so I will take a look, but it may be a day or two: I don't have USI ls installed at the moment and am also still in the process of moving... Sooooo, priorities :)

**Comment by jmrd98** [comment]
Simplest short term maybe to disable the cfg until a proper upgrade can be made. I'm also on mobile at the moment, which is difficult to github with.

**Comment by JohnnyDeuxMille** [comment]
Is this something you still need help with? Maybe I can contribute.

**Comment by jsolson** [comment]
The consensus seems to range from it doesn't require anything, to it doesn't require anything but lets do something anyway. I don't use it myself.

**Comment by jmrd98** [comment]
Honestly, It needs to be moved to the extras folder at the very least, or disabled until a new one can be implemented as the current one doesn't work with the current USILS. 

Why I created the thing in the first place was for the station parts and the (re)supply modules, much more so than the crewed parts. Whatever update/replacement that comes in ought to focus on those. But, disable it in the meantime for certain.

**Comment by jsolson** [comment]
That make sense. TAC-LS only needs a few little tweaks, and then probably the same for resupply modules.

**Comment by jmrd98** [comment]
I was going to comment this on the second to last commit, but it's better placed here.

Is there a plan at all for config/balance of the ETS Apollo derived supply module? (Aardvark?) I had started roughing one in when working on the Snacks! config, before thinking I had no idea what it ought to do. I know the model / texture are not final, but it was worth a thought. Hopefully the (now 4) resupply modules follow some sort of trend, linear or otherwise.

A decision also could be made on gameplay: Is/should the Agena based module designed as a pseudo historical stopgap to be outclassed by the later/larger models, or does it have a niche to fit in, etc? Basically, the difference between them just being different sizes but otherwise the same, or having a more defined role for each. I would like for the second, but I think practicality demands the first one, in the short term at least.

**Comment by jsolson** [comment]
I overlooked the Aardvark. The way I handled the others was to calculate the volume the same as any other tank, then make it an Ore tank. The Ore resource gives us something to hook into with MM and provides volume information. So the Aardvark would be 2400 units (1 unit = 5 liters). Then we just use B9 to add a tank type with resources for whichever LS mod is installed.

For TAC all the resources are in liters so that was easy. For USI I'm not sure how Supplies are setup. They might be 1 unit = 5 liters like stock resources, or they might be 1 unit = 1 liter like real resources in CRP. Someone familiar with it should look at the parts and see if the amounts make sense - compare them to USI provided containers.

I don't know if I would call the Agena module a stop gap. An Augustus (Gemini) resupply module loaded up with about 90 days of supplies for 3 kerbals took a Delta class launcher to lift to orbit. The Agena module holds 1/3 of that, and should be cheaper to orbit, especially with an Agena D behind it.

>E: docking rcs on an Agena is a pain in the ass every time I've tried ><

I imagine it would be if you don't add extra thrusters to balance it out.
