### ISSUE TITLE
Real names config

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#251]
Some people want a real names config, so I figured I'd create an issue for it. I'll do what I can, should be fairly simple, if tedious. I presume you want an MM patch?

**Comment by CobaltWolf** [comment]
Yes, an optional MM patch. Maybe put it in an 'Extras' folder in the download? Along with stuff like more realistic textures.

**Comment by IronCretin** [comment]
I'm afraid I can't do textures, but I'll do what I can for config stuff.

**Comment by CobaltWolf** [comment]
Other people were working on those.

**Comment by jsolson** [comment]
I would love this for probe cores if nothing else. I do wish the makers of this mod had thought to put "based on real world whatever" somewhere in the part description :-)

[bdb.cfg.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/539266/bdb.cfg.txt)

That's a config I've had laying around in an old install. It's far from perfect, but it might help knock out 90% of the work. If there are problem parts it might be simpler to re-title the part than write a big complicated script.

**Comment by CobaltWolf** [comment]
Oh shut up :P

**Comment by IronCretin** [comment]
Wait, you can do text replace in MM? O_o

**Comment by jmrd98** [comment]
Yes, check their page/wiki for some regex examples, although Jso just gave some good ones in that file... I'll update when I get off mobile.

**Comment by CobaltWolf** [comment]
@IronCretin I'm closing this now

**Comment by jsolson** [comment]
Hang, he's not off the hook yet...

The Agena 100/100W tanks were recently renamed 60/60W.

The Saturn parts don't group by stage. I'd strongly recommend removing references to capacity. I'd also remove vehicle references such as "Saturn V S-II" and just name everything by stage, i.e. "Saturn S-II".
The BLI-XXX-XXX naming convention on interstages is a holdover from when everything got thrown into the Structural category. Since we have a Coupling category now I think that convention is outdated, and you could probably name these parts just by stage. Although I would leave it for now on the pure do nothing structural parts, none of which belong to Saturn.

**Comment by CobaltWolf** [comment]
Hrmm, I agree. Are you planning on renaming said decouplers in the mainline release, @jsolson ?

**Comment by jsolson** [comment]
Now that you mention it, yes I will. It makes sense for the interstages. For the pure decouplers (BDD-xxx)... sorting them by size is still useful I think. I'd hate for them to be scattered randomly around the Coupling tab.

**Comment by CobaltWolf** [comment]
Remember that they can sort by size... I say that because I think the naming convention is ugly :P
