### ISSUE TITLE
BALANCE: Prometheus-I hydrox engine balance

### ISSUE THREAD

**Issue by minepagan** [CobaltWolf/Bluedog-Design-Bureau#265]
Compared to engines at this tier from the CryoEngines mod, the engine is extremely underpowered. Reccomend increasing research cost, and at least halfing unit cost.

**Comment by CobaltWolf** [comment]
Note that I checked, the ISPs are correct and the thrust (obviously, reduced due to the efficiency) and weight are comparable to engines in that class.

**Comment by jsolson** [comment]
I agree. Drop the cost. We could drop the mass to 1 ton too. The 1.25m butt plate has kept me from playing with this part. I've wanted to try a cryo second stage on titan.

**Comment by CobaltWolf** [comment]
I was thinking about that too, maybe make it a mesh toggle. In general having toggleable butt meshes for all the engines would be great... I want to get more use out of that engine so I might tackle that soon.

I am a bit confused since the description of the engine on Astronautix doesn't really explain what the use for the engine would have been - lifter, vacuum... They mention it as being a competitor for the J2 but that's probably because it was the only existing option for the kind of thrust they were looking for; there is an physical upper limit for how big an expander cycle can be. So it probably could have been both an upper stage, or a lower stage for smaller launchers.

Maybe add a single of the Titan IV first stage nozzle as well? They have pretty different performance.

**Comment by CobaltWolf** [comment]
@jsolson yay or nay on throwing in a single mount of the LR-87-11 (the last model)

**Comment by jsolson** [comment]
By all means, do the whole family. 1/2 thrust, mass, cost. Can anything be done about the hovering buttless version? I don't really have a suggestion, that is the whole engine, and I can't imagine a shifting top node is a good idea.

**Comment by CobaltWolf** [comment]
Not really... I think the best option would be, once Angel's autoShroud switcher is in (he said he's doing it this weekend..?) to just have a shorter fairing and let the player use the translate gizmo to move it up.

**Comment by IronCretin** [comment]
Can you tie the mesh switch to the stock node switch? It'll still be on the old node, but if you take it off and put it on again, it'll go on the lower node.

**Comment by CobaltWolf** [comment]
there's a stock node switch?

**Comment by minepagan** [comment]
Yeah, like with interstage nodes on fairings, right? You can toggle them on and off.

**Comment by CobaltWolf** [comment]
B9 lets me toggle nodes on/off...

**Comment by CobaltWolf** [comment]
@jsolson so I think I'd like to try and make one with a larger nozzle to serve as a vacuum version. In the meantime, the lifter versions can have their numbers changed in line with what the RO people dug up on it. That gives the lifter version 200.25 thrust and 358/409 ISP in the most advanced form, we can start with the initial Titan C version if we want to do part upgrades. The entryCostSubtractors thing - is that stock? It'd be super useful for us - the Titan SRBs, for example, should all need separate full development costs I think.

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/Parts/Engines/LR87LH2.cfg

**Comment by jsolson** [comment]
Done. https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/2cc154bc49cfce9b3b30db7c425c86fee41dc9a7

The upgrades come in with the Titan IV engines. Just need a model for the vacuum version. I deviated from RO's hypothetical numbers and lowered the sea level isp on the vacuum version to 20, otherwise that engine will have more sea level thrust than the sea level version due the way we buff the vacuum engine's thrust. It's also twice the weight for balance.
