### ISSUE TITLE
Finish Skylab parts

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#290]
Not for this release, but they need to get done...

**Comment by jsolson** [comment]
I updated the skylab parts with new mass numbers. It should be coming in at a little less than 50 tons. @Daelkyr13 you did a really good job on these configs, I only changed anything in the lab because I gave you two different mass numbers for that part. I have not looked at cost yet.

Some issues... I don't use MOLE so I'm unfamiliar with expected behavior.

A. Module WBIPowerMonitor is spamming errors in the log. It looks like it's looking for a resource converter which is only present in the WBI lab configuration. That module should probably be moved there.

B. The stock lab is always present and apparently functional, even in tank configurations.

C. It always holds crew, even in tank configurations.

D. Given that the WBI patch is a significant change to the part configuration it's likely save breaking in the event someone builds something without WBI, then later installs one of Angel's mods - unwittingly triggering our patch. Perhaps this would be better done as an additional part using a +PART[] patch, with a stock skylab part and a wbi enhanced skylab part.

**Comment by CobaltWolf** [comment]
Jso my only fear with that is, if someone using MOLE uses somone's craft file (the ones linked in the OP, for instance) then the craft file wouldn't be MOLE compatible, would it?

Also, @jsolson can you try and figure out a role for Skylab in stock? In addition to making it a combined hab/lab segment, I feel it needs additional capability. Maybe some built in custom experiments, maybe have them use the functionality that DMagicScienceAnimate gives us since that's still dependency for a lot of our experiments.

Additionally we need a solution for the Apollo Telescope Mount. IRL, they frequently did EVA's to change out the film cartridges for the experiments. I'm trying to think of how we can go about this.

**Comment by jsolson** [comment]
If they were separate parts a stock lab craft file would load fine on any install. A MOLE lab craft file would not load on a non WBI install.

I'd really like to split it in half and make a lab part and a hab part. We've kind of learned to be cautious with the kitchen sink approach so I wouldn't try to stuff experiments in there. Some sort of equipment bay would be more stockalike. Split it in thirds; Lab, Hab, Equipment Bay :-)

I think the MDA needs to have the ModuleCommand removed. The IU provides that. It might confuse third party patches that hit command pods.
