### ISSUE TITLE
BALANCE: Cost/Payload Capacity balance between Sarnus, Prometheus and stock.

### ISSUE THREAD

**Issue by KuuLightwing** [CobaltWolf/Bluedog-Design-Bureau#300]
Hi!

I've tested several rockets and their payload capacity in 2x kerbin system, which AFAIK the mod is somewhat balanced around.

Prometheus IV costs about 40,000 kerbucks and can lift about 22,500kg into low orbit:
http://imgur.com/a/IW3Z6

This stock rocket costs about 50,000 kerbucks and can lift the same payload into LKO. It's a bit weird in the sense that it has a low TWR upper stage which required a burn time like 3 minutes, but it's not that hard to do:
http://imgur.com/a/DyzsP

Both rockets had about 4,500m/s of vac dV and there was some margin for error.

And then there's Sarnus 1C. First of all, it's much more expensive than the first two rockets - it costs 90,000 kerbucks. Second, it to have the same vac ISP as the other two rockets I had to reduce the payload to 18 tons. And in the end I wasn't able to get it into orbit at all:
http://imgur.com/a/iJWsc

The reason why with the same vacuum ISP Sarnus can't get into orbit is because it loses much more ISP in the atmosphere since Mainsail and Kickbacks don't lose that much, and Prometheus is lifted up in the atmosphere with her SRMs (that also don't lose that much ISP in atmo) before the liquid engine starts.

The cost issue, however probably needs to be addressed... somehow. Prometheus seems to be somewhat underpriced compared to stock - probably the engines and SRMs could see an increase in price. There's nothing in stock even closely comparable to those SRMs. 

Sarnus (IC and IB as well) is just too expensive and offers less capacity that Prometheus and stock rockets. I guess the game is not just about heavy lifting, but on the other hand, there probably should be some reason to build Sarnus rockets.

EDIT: A similar issue is with Saruns I and Prometheus III - the latter has better payload capacity and is much cheaper. They are also available roughly at the same point in KSP career.

**Comment by jsolson** [comment]
Our Saturn is undersized. About 56% rather than 64%. Keep that in mind when comparing anything Saturn to non-Saturn.

Cost in stock is arbitrary. The the formula we use for tanks per fuel unit is base cost + fuel + arbitrary rounding up. We don't control fuel costs. Base costs are:
Standard: $0.70
Balloon or Cryo: $1.82 (you're paying for 60% less dry mass)

A tank with a volume of 100 would cost:
Standard: $115.90
Balloon: $227.90
Cryo: $200.28
Note that the Cryo tank has a lighter fuel mass than the other two so you get less but hopefully you make up for that with higher Isp engines and an overall lighter dry mass.

Engine pricing is 100% arbitrary. There are conflicting factors and I've never seen a formula that can really pin them down. At a glance we look to be ok with stock engines but we can always revisit specific cases.

Solids... need a balance pass. Looks like were just paying a token amount over fuel cost. I'll try to come up with a formula for those. LFO costs $0.46 per unit, SF $0.60 per unit. SF always has a lower Isp so it's costs more for the same DV, but the SF itself is the engine, so you save there.

**Comment by KuuLightwing** [comment]
High costs for Sarnus doesn't seem to come from fuel. For example, "dry cost" of Sarnus IB is ~68,000 kerbucks:

- 8 first stage engines cost 1,200 - 1,300 each, which makes it 10,000 only for first stage engines. 
- The tanks cost 9,820 and 20,560 respectively (without fuel)
- An engine mount for Sarnus IB costs 5,000
- S-IVB engine mounts adds 2,000 on top
- Interstage adds another 4,500 kerbucks

So, it appears that the biggest problem is the tanks. Prometheus tanks don't cost nearly as much (as they all combined take less volume than Sarnus I first stage on itself), and I might suggest that the formula you use for tank cost might just not be the best idea here.

Also, structural elements for Sarnus IB cost 11,500 kerbucks on their own, while Prometheus doesn't even use any. I believe that it's just way too high.

As for solids - I also noticed that one of the Prometheus boosters (Sultan) was roughly comparable to Kickback in terms of thrust and other parameters, while costing 1,600 compared to Kickback's 2,700 (empty cost - 90!). So, yea, probably their cost needs to be addressed. 

And in general undersized or not, there should be some reason to use Sarnus other than that Kane fits it better. I compare them from the perspective of using them in Career - because if I want to lift some heavy payload into orbit, Prometheus family just does it better. Sarnus, unfortunately feels underwhelming because it's supposed to be a heavy lifter, but you can't really do that much "heavy lifting" with them.

**Comment by KuuLightwing** [comment]
Also, It appears to me that while cryogenic tanks indeed have less dry mass per volume, their mass fraction is also worse. Standard mass fraction for Kerbal tanks is 9. But for Cryo tanks it becomes 7. And cryo tanks have much less density, which is expected, but because we're paying more per unit of volume, and carry about one third of the propellant (by mass), this makes them vastly more expensive than regular LFO tanks. Sure, they are lighter, and higher ISP does help somewhat, but it's just not nearly enough.

**Comment by jsolson** [comment]
Structural parts can be addressed. I doubt think they've ect been looked at from a cost standpoint. Engine mounts should cost 0 since the cost is in the engine. They just need some not silly number.

**Comment by jsolson** [comment]
Probably going to do something with cryo/balloon tank cost, just not sure what yet. If you want to play, the cost can be adjusted in `GameData\Bluedog_DB\Compatibility\B9PartSwitch\B9TankTypes.cfg`. The bdbLH2O and bdbBalloon are the types in question.

FWIW, a Titan IV-Saturn 1C comparison should show a cheaper Titan IV. The Titan has a significant and cheap all solid first stage, while the Saturn has a very large and expensive cryogenic second stage. A more apples to apples comparison might be a Titan III first stage with a Centaur second stage vs a similar performing all LFO Titan III. No solids on either.

**Comment by KuuLightwing** [comment]
It's fine if some rockets are slightly more or less expensive than the others, it's just in this case the difference is a bit too noticeable.

I tried to tweak the config you mentioned (halved the cost for LH2 tanks), but it doesn't change the cost of hydrogen tanks. However, when I switch fuel type, it changes them into very expensive LFO tanks. LFO tanks, in turn turn into slightly more expensive LH2 tanks - like they should. I assume their base cost is defined somewhere, and all the calculations are done from that cost, because when I change the values back - LH2 tank costs the same, but when I switch it to LFO tank, it turns into a much cheaper tank.

Also, I found out that Sarnus IC can actually lift 18 ton into orbit - the one in my save had less fuel loaded into second stage for some reason. Not much more than that and it requires pretty careful flying, but at least that works. 

And, by the way - there's another LV in the same payload capacity category - Muo V and I toyed with it a bit yesterday. It costs about $55,000 for 552 variant, and lifts about 18 tons into orbit - same as Sarnus IC. Stretched Inon doesn't hurt the cost that much, even though it's cryogenic, it only costs ~$12,000 and only half of that cost is tanks. I general, I do not think that halving the cost for cryo tanks would hurt anything. Small upper stages would get slightly cheaper, but not really that noticeable, while it will help Sarnus rockets a lot.

Also, I think that structural parts for Sarnus could be even cheaper. Like interstage is basically a glorified decoupler - and decouplers in stock don't cost more than $600. The one for S-IVB costs $3000. And engine mounts too - they could be compared to bi- and tri- couplers, which are also very cheap. they're kinda a tax to make Sarnus look right.

**Comment by jsolson** [comment]
I guess I'll have to recalculate the tank cost in the part.cfg to test this in game. Thankfully there's not too many cryo tanks and it's easy enough to estimate for now. I'm tempted to drop it down to $0.70 (same as LFO) to $1.00 because the Centaur is horrifyingly expensive compared to similar LFO options. I'm not inclined to change the Balloon cost (Atlas/Agena D/Vega) at the moment because that does provide a definite performance benefit.

I attempted to lower the interstages further by calculating the cost as if it were a decoupler + p-fairing (this is something we have good numbers on and can nail down), but the cost works out to close enough not to bother. The biggest savings was $800 in the S-II interstage. All the non Saturn interstages got more expensive.

I also attempted to balance the mounts against the bi-tri-couplers with a size+hardpoints types calculation, but the 8 hardpoint S-I mount blew that out the water so I just eyeballed them. They just need to be about the same as other similarly sized do nothing parts.

**Comment by jsolson** [comment]
I may be crazy but I think this makes sense from an economic standpoint. The dry mass per 1000 units of LFO tanks is 0.625T, and cryo is 0.25T. 0.25/0.625 = 0.4 * $0.70 = $0.28

LFO: $0.70 per unit. That works out to $140 per ton of fuel carried. $231.80 per ton including fuel cost.
Cryo: $0.28 per unit. $184.73 per ton of fuel, $305.35 including the fuel.

In the same 1000 unit tank, fully fueled:
LFO: $1,159.00, 5 tons fuel.
Cryo: $462.81, 1.52 tons fuel.

I've got Balloon tanks at $0.92365 per unit right now. That makes them $184.73 per ton of fuel, same as cryo, and 276.53 per ton including fuel cost. Not sure which way to go here.

Solids base cost is $60.00 per ton of fuel, $140 including the fuel cost.

**Comment by KuuLightwing** [comment]
Hmm... I actually didn't think about that much of a cost reduction.  I thought about bringing them down to 0.7 or maybe even slightly higher, but on the other hand, this brings Sarnus cost to 60,000 and 52,000 for IC and IB variants respectively, which is much better than before. 

And Prometheus IV is still the cheapest and most powerful LV available, so solids could use another price increase, I suppose, because the biggest ones only ~$1200 more expensive.

I honestly didn't touch balloon tanks all that much. The thing is that vehicles that used them don't have that much volume, so cost of tanks was not that big fraction of the vehicle cost like it was with Sarnus. I guess they could get some cheaper, but their old cost was not that bad, AFAIR. They have mass fraction of like 21, which is really outstanding by KSP's standards, after all.

**Comment by CobaltWolf** [comment]
Honestly the components of the Titan IV... the engines and the SRMs... could maybe be increased in price? I mean, it was a ridiculously capable rocket IRL, surpassing even the Saturn 1B. BUT it was hideously expensive, and had a 1 in 10 failure rate. Problem being, a lot of the expensive was because it still used massive amounts of hypergols - remember, after the USAF stopped using them, nobody wanted to deal with these dangerous substances - and that is an issue since it uses the same fuel as everything else in KSP...

**Comment by jsolson** [comment]
I forgot to copy the Titan solids in the original commit but got them in this one: https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/858e562c7363f5800b575205aaa0d07efade33bc - they all went up in price, you guys want more?

**Comment by KuuLightwing** [comment]
I mean... the biggest offender is Titan IV which costs like $35,000, and this only makes it cost ~$37,000.

**Comment by jsolson** [comment]
I can try some kind of a curve on SRB pricing. The problem is we're balanced against the Kickback, which the Soltan approximates so pricing would need to curve up from there. To get the kind of cost bump we need you'd end up with 8 Soltans clustered delta style being cheaper than 2 big solids Titan style.

There's probably a lot of changes we could make on engine pricing, but the only glaring issues I see relative here are the Atlas V engine being too expensive, and the J2's are too cheap.

**Comment by KuuLightwing** [comment]
Kickback has some disadvantages vs Titan boosters, though. First is no thrust vectoring. Second - no thrust curve. Titan SRMs start off even higher than rated thrust and then drop off thrust a bit so that the acceleration doesn't get ridiculous as SRBs burn out. Those two things make Titan SRMs much more convenient to use. 

Some curve would be nice. Yea, probably clustering smaller SRM would be cheaper, but it would be much bulkier, and that increases drag, complexity and wobbliness of the whole thing.

J2 costs could be tweaked a bit - it would affect mostly Sarnus V and Sarnus INT-21, which after the cost reduction for cryogenic stages are about $230,000-260,000, which is a pretty good price for an LV that can lift 80+ tons into LKO. So, as long as J2s are not getting too expensive, that should be fine.

**Comment by jsolson** [comment]
I'm uncomfortable with this Titan IV/Saturn 1C comparison so I want to build some rockets and get some cost/payload ton numbers before proceeding. Hopefully it doesn't confuse things even more.

The J-2 (and F1 and maybe others) cost should include the mount for balance purposes, so it's probably ok. With that in mind it would make sense the S-IVB mount is 1/5 the cost the S-II mount. Same for the S-IE and C mounts.

**Comment by jsolson** [comment]
[Some numbers to chew on](https://docs.google.com/spreadsheets/d/1CwAsJiTm4MtPLIFbabFLs1MFDhLSpQiUAsVMl-YKgB8/edit?usp=sharing)

The cost of radial decouplers ($600) severely impacts the cost benefit of using solids with the smaller engines. Some $6000 monster size decouplers for the 12xx boosters would pretty much solve the problem. We'd just have to force people to use them.

Thor is terrible. Even if the engines are free. It's got to be the lousy Isp on the early engines.

Athena looks good to me next to the others. It's cheaper, but not ridiculous.

Increasing the cost of the big 12xx boosters by 250% would pretty much level things out and eliminate the better cost/ton when using those boosters.

**Comment by KuuLightwing** [comment]
Or... maybe we need a decoupler for smaller SRBs. Or, better integrate decouplers in there if possible (I suspect not quite). Titan boosters are indeed really good. But, are you sure about 250%? That would make Titan IVB boosters cost ~28,000 each, which strikes me as a bit of too much. Or you meant not BY 250% but TO 250%? Still, it's about 20,000 kerbucks each. Well I suppose that could work. Would it affect Saturn multibody, though? 

Also did you calculate Atlas V cost without Centaur?

**Comment by CobaltWolf** [comment]
We need a decoupler for the smaller radials as well, I'm working on it but its even less of a priority.

**Comment by jsolson** [comment]
I mean cost * 2.5. I stuck a few extra rows in the spreadsheet so you can see the impact. No Centaur on Atlas V. Thor's numbers in practice are probably better. The 5500dv is a ballpark this will defiantly make orbit and then some number for 3x. Smaller rockets get away with a lot less (drag losses maybe?).

Combining a decoupler and engine is a problem for MechJeb/KER's dv math. And creates a staging problem - you can only stage a part once.

**Comment by KuuLightwing** [comment]
Well new numbers look good. I totally still would use Titan IVB at $60,000 and since cost-per-kilo becomes more consistent, that would be a good thing. 

As for Thor... honestly, it fills a really small niche, because launching small things into low orbit doesn't serve a lot of purpose in KSP. The most useful rockets are the heavier things - like Titan, Atlas and Saturn. Or maybe I'm just playing the game wrong.

**Comment by jsolson** [comment]
The formula I'm liking is going to put the Soltan at $5400 vs $2730 for a Kickback, and the 1207/USRM's in the $20,000 range. That gives you the $60,000 Titan. The smaller engines won't be effected.

I put together a formula that pretty closely tracks Squad pricing for liquid engines. The lower stages look pretty good, other than Atlas V and all the Titan engines being overpriced. The upper stages on the other hand are all over the place. We're looking at a do-over on those.

**Comment by jsolson** [comment]
[Changes](https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/ada482d31d289683f6a2658b8cab08ffc242479b). I think I got 'em all.

**Comment by KuuLightwing** [comment]
Sorry for going silent - can't check the new costs right now as the dev version makes all the tanks disappear. But if they reflect the spreadsheet you posted before, that should be good.

**Comment by CobaltWolf** [comment]
@jsolson the $113,000 AJ-260 is very expensive compared to a normal S1 stage.

**Comment by jsolson** [comment]
A Titan IV core is $15,950 vs $18,000-21,000 for each booster.

What are you comparing to?
SI $27,100
SIC $153,000
SIE $31,000

Over-simplifying, but each Kerbal AJ60 can lift an additional 300 tons. The Titan boosters add 60-70 tons.

**Comment by CobaltWolf** [comment]
Hrmm. I mean, looking now I definitely can't find anything that suggests that this was intended as a cost saving measure as I had originally thought. So maybe it's not that out of line. Regardless, the cost still seems extreme. I'd think maybe 60-80 thousand seems more appropriate? 

Also why is SIE more expensive? I'm more curious just at what makes it cost more (the F1?), not saying it needs to change.

**Comment by jsolson** [comment]
>Also why is SIE more expensive?

Structure, without fuel, engines, fins, etc:
SI $12,320
SIE $8,324
(I can't explain that discrepancy)

The engine prices make sense to me:
H1C $940
H1D $1,160
The eight engines for the SI total $8,400.

A single F1A is $16,250 (F1 is $13,000).

**Comment by jsolson** [comment]
This is what the S-I class looks like now with the S-IE/F adjusted for balloon tanks costs.

S-IB $29,610 entry level, three styles of cool fins
S-IE $42,910 easy build, more thrust, more fuel, more Isp
S-IF $49,390 more fuel
AJ-260 Short $55,600 trades Isp for more thrust
AJ-260 Long $113,810 double fuel, thrust

**Comment by Pappystein** [comment]
To the original post (That I some-how never saw) a key factor into calculating ISP (which is what started this whole journey,) is the DIAMETER of the launch vehicle.  A long 1.875 stack will NATURALLY have a Higher ISP per ton of payload than a 2.5m diameter stack.  Original comparison was apples to pears.. same family but not real close.
RE the "Low cost option"  Cobalt the AJ-260 was part of one of the Boeing LCB proposals for Saturn I cost reductions.  It specificaly states in the proposal that both building it on site and the fact that there is only one "segment" to fill brings about it's reduced cost vs similar sized SRMs.   I suggest the cost formula for Solids should take into account the number of Segments.   I don't know a straight linear modifier, of sorts where the number of segments directly impacts the modifier.   Each SRM has the following processes during construction.  the steps marked * are where processes are duplicated.

- Build fuselage*
- Initial Hydrostatic test*
- Build mould to specific grain pattern for this launch (1/2* as several segments will have the same grain and some will not)
-Pour Solid fuel into fuselage and mold (for the grain)*
-Test the pour.*
-Ship to launch site
-assemble the segments*
-test the Segments (Segmented only!)
-Dis-assemble for inspection of O-Rings (Challeger fallout)*
-Re-assemble in the VAB or similar structure on Rocket*
-Roll out and launch.

So in my simplified plan you have 6 or 7 points of cost reduction because the AJ-260 is a Mono-hull SRM

**Comment by jsolson** [comment]
At this time the approach I support is reducing the large SRB tax* from 550% to 200%. This would make the AJ-260 Short $27,850, and the Long $56,200. The UA-1207 would drop from $18,461 to $9,688 returning the Titan III/IV to most cost effective heavy platform. Since there are many Saturn proposals that also make use of the UA-1207's, they too will benefit.

*_The SRB Tax is applied to the base (non-fuel) cost. The first $600 is exempt._

**Comment by CobaltWolf** [comment]
Sounds good to me John. Fuck it.

**Comment by jsolson** [comment]
FWIW converting Titan to use Aerozine50/NTO would address it's cost concerns due to the much higher cost of that fuel ($614/ton) vs LFO ($92/ton). I am not suggesting we do that.
