### ISSUE TITLE
BALANCE: MOS Lab generates science too slowly.

### ISSUE THREAD

**Issue by KuuLightwing** [CobaltWolf/Bluedog-Design-Bureau#311]
Now, I noticed that a while ago, but only recently I tested to confirm the issue. The problem is that MOS lab is about a 100 times slower than stock lab when it comes to converting data to science. I understand it being smaller as a reasoning for less data/science capacity, and slightly slower science production rate, but this is far too extreme - it makes the use of this lab for the purpose of science a bit questionable. 

Here's the test craft: 
![Test craft](https://cdn.discordapp.com/attachments/206181796164009984/288845348930322432/20170308042644_1.jpg)
Both labs have the same amount of data and two level 5 scientists.

**Comment by jsolson** [comment]
I'll see if I can decipher the stock lab config. How should the MOS lab behave relative to the stock one? I don't use them much myself.

**Comment by KuuLightwing** [comment]
Honestly, I think there's no need to change the science rate, because the MOS lab is already "nerfed" compared to stock one due to reduced capacity. But even then you can make it like 2 times slower, and it wouldn't make MOS lab all that bad. It's when it 100+ times slower - that's where it's a problem.

**Comment by jsolson** [comment]
@Daelkyr13 is still working in these files for Skylab so I'll stick this here for now so as to not screw him up.

Proposed changes. 60% of stock numbers for mass, cost, data/science storage and science return. I believe the smaller storage will slow it down - or maybe speed it up. The lab is weird.
~~~
	entryCost = 7200
	cost = 2400
	mass = 2.1

	MODULE
	{
		name = ModuleScienceLab
		containerModuleIndex = 0
		dataStorage = 450
		crewsRequired = 1
		canResetConnectedModules = True
		canResetNearbyModules = True
		interactionRange = 5
		SurfaceBonus = 0.1
		ContextBonus = 0.25
		homeworldMultiplier = 0.1
		RESOURCE_PROCESS
		{
			name = ElectricCharge
			amount = 10
		}
	}

	MODULE
	{
		name = ModuleScienceConverter
		dataProcessingMultiplier = 0.5 // Multiplier to data processing rate and therefore science rate
		scientistBonus = 0.25	//Bonus per scientist star - need at least one! So 0.25x - 2.5x 
		researchTime = 7	    //Larger = slower.  Exponential!
		scienceMultiplier = 3	//How much science does data turn into?
		scienceCap = 300	    //How much science can we store before having to transmit?		
		powerRequirement = 3	//EC/Sec to research
		ConverterName = Research
		StartActionName = Start Research
		StopActionName = Stop Research
	}
~~~

**Comment by LouisB3** [comment]
Lab science rate formula is discussed [here](http://forum.kerbalspaceprogram.com/index.php?/topic/67992-121-taurus-hcv-375-m-csm-system-v153-july-1-2014/&page=29#comment-2839973) on the forums, in the context of balancing a (large) science lab. The formula is:
`sci/day = dataStored * scienceMultiplier * sumScientistStars * scientistBonus * 1/10^researchTime * 22680`

**Comment by jsolson** [comment]
If I've got it right, with those numbers, and the same amount of data and scientists, all three labs would perform exactly the same. Is that what we want?

**Comment by LouisB3** [comment]
They should perform the same on a science-per-day-per-ton basis, yes. So the heavier labs would be proportionally better than the lighter labs on a per-mass basis, and vice versa

**Comment by jsolson** [comment]
I can't confirm your calculations. dataProcessingMultiplier isn't in the formula. I've never found a definitive answer to what the actual formula is.

My understanding is with your numbers given the same 100 data, and the same level 3 scientist, all three labs would produce exactly the same result. It's not until the bigger labs hold more data (or scientists) than a smaller lab can support will there be a difference. That's my question, do we want that?

**Comment by LouisB3** [comment]
Ah ok, I see where I misunderstood you.

The formula is actually `sci/day = dataStored * scienceMultiplier * sumScientistStars * scientistBonus * 1/10^researchTime * 22680 * dataProcessingMultiplier`. The original version was determined experimentally [here](http://forum.kerbalspaceprogram.com/index.php?/topic/116534-questions-re-cfg-file-parameters-for-science-labs/#comment-2087921), and the dataProcessingMultiplier term was added to stock in a subsequent bugfix+balance update. 

Re: data amounts... yeah, that's pretty much how it works. Processing speed is proportional to the amount of currently stored data. That means that the benefit of larger labs would be greater storage and/or crew capacity.

Given the formula we have to work with, here are the variables we can choose between modifying:

- Increasing data storage means that the lab can hold more data, which is nice because it decreases micromanagement somewhat (reduced risk of experiments being too "big" to fit in the remaining space). It does mean that we need to gather more data in the first place to benefit from the larger lab, but I don't see gathering experiments to be a huge barrier initially; as the lab is being launched, you can grab results from the pad, two layers of atmosphere, low space, and wherever its final destination is.
- Increasing the science multiplier would actually increase the amount of science each unit of data produces, which would end up increasing the effective lifespan of the lab. Each lab can process any given experiment result only once, so once you run out of local experiments you would need to import more from elsewhere to keep the lab running.
- scientistBonus changes how productive each scientist is based on their level, which I think would be confusing to change.
- researchTime is an exponential change and I believe it only accepts whole numbers, so not appropriate.
- dataProcessingMultiplier - I guess this would be the absolute simplest change as speeds processing and has no secondary effects. If you do end up changing this, it would benefit from testing to confirm it's behaving as expected, since the effects of this term have been tested less thoroughly than the others.

I like tweaking the data storage personally, partly because it involves the smallest change from the existing configuration, but it might come down to which, if any, secondary effect is preferred.

**Comment by CobaltWolf** [comment]
I think it comes down to what sort of purpose they have. The MOL lab is meant to basically prototype what it means to work in space long term, and figuring out what sort of stuff can be done with that capability. It also has to provide access for EVAs and some limited habitation. It has barely enough room for two Kerbals to work, and I imagine them often taking refuge in the capsule in shifts to get away from each other. So not much is going to be done there. We also wanted to make the 1 man mercury lab but were somewhat dubious on what it could actually accomplish in game (personally I'd be fine if it was capable of just generating maybe 30 science over multiple missions before the player moves one), however if there is some space for that in the progression I'd like to see it.

Meanwhile, (unlike in real life...) the Skylab will have to represent a more mature capability, with large workspaces full of experiments, though with only ~2/3 the volume being used for that type of stuff, maybe less. They have a lot of room to play around with in there, and can work in relatively lavish comfort as far as space living goes; Skylab's layout is fairly wide open, to the point they almost ran into issues getting stuck floating in the middle, even with a system of grates in place for astronauts to grab onto!

If we could, I'd love to see that reflected in the scientistBonus, but if that value isn't exposed to the player, oh well. Data storage is somewhat of a given, and I believe we can scale it somewhat linearly with a given volume. Having a science multiplier of <1 for the earlier labs would maybe achieve the same thing as scientistBonus.

**Comment by jsolson** [comment]
I'm in agreement CW. I find the formula suspect though.

`sci/day = dataStored * scienceMultiplier * sumScientistStars * scientistBonus * 1/10^researchTime * 22680 * dataProcessingMultiplier`

simplified is:
`product of most everything * 10^-7 * 22680`

I have two problems with that. With a zero star scientist the answer is zero. Do labs produce anything with just a zero star scientist? (Edit: a quick test says they do). There are 21600 seconds in a 6 hour Kerbin day, so what's 22680?

Edit: The formula is likely close to `sci/6hr day = dataStored * dataProcessingMultiplier * (scienceMultiplier + sumScientistStars * scientistBonus) * 10^(-researchTime) * 21600`

The confirmed formula for resource converters is `Efficiency = EfficiencyBonus * (SpecialistBonusBase + SpecialistEfficiencyFactor * Sum of Stars)` so that would be similar to another known Squad formula using Kerbal stars.

**Comment by LouisB3** [comment]
CobaltWolf: good points about the relative capacities of the designs according to their volume. I think that this meshes well with the suggestion to scale the data storage with the mass of the part: it will be visible to the player that lab size is proportional to storage capacity; and it will also automatically scale the performance of the part without further messing about with the more obscure variables. If we distort relative performance even further, the MOS will be effectively useless (as in the original report above) and the Skylab will maybe unlock the whole tech tree immediately.

Jsolson: nice observation that the previous formula cannot account for zero-star scientists. (I hadn't noticed it before, as I tend to train my crews as much as possible before sending them to toil in the science-lab mines.) The formula you propose doesn't quite match up with the results I recall from my testing, but ultimately this all just illustrates how aggravating it is that Squad never bothered to share the details of this overcomplicated formula with players and modders. Also, not to get off-topic, but I was under the impression that resource converters only care about the highest-level kerbal available, not the sum of the crew's stars.

**Comment by jsolson** [comment]
Slightly changed formula and added number of scientists. Can't find a scenario where this fails:

`sci/6hr day = dataStored * scienceMultiplier * dataProcessingMultiplier * (numScientists + sumScientistStars * scientistBonus) * 10^(-researchTime) * 21600`

Internally what I think is happening is data is processed at `dataStored * dataProcessingMultiplier * (numScientists + sumScientistStars * scientistBonus) * 10^(-researchTime)` per second. Since `researchTime` is useless as an integer variable, they gave us `dataProcessingMultiplier` to control the rate.

The processed data is then multiplied by `scienceMultiplier` and stored as science up to the `scienceCap`.
