### ISSUE TITLE
COMPATIBILTY: RealFuels issues

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#312]
The files are in [extras](https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/master/BD_Extras%20(No%20Warranty)/RealFuels-Dev). They go in GameData\RealFuels-Stockalike\BDB. The major work on the engines and tanks is done. Probably a lot of RCS glitches and inter mod compatability (mainly TAC-LS) to sort out. This will be turned over to the RealFuels-Stockalike mod once stable.

**Comment by Meltdown19** [comment]
There is a typo in vega.cfg at line 109 : 

`maxThrust = maxThrust = #$/MODULE[ModuleEnginesRF]:HAS[#engineID[Vernier]]/maxThrust$`

**Comment by jsolson** [comment]
Got it. You'd think that would throw an error.

I'm seeing odd behavior on Apollo. The "left" and "right" side rcs quad thrusters don't fire, while the "top" and "bottom" do. I can't imagine what config mistake could cause that.

**Comment by Meltdown19** [comment]
Absolutely nothing wrong with defining the maxthrust this way, it just looks cleaner without it (*pseudo* def foo = foo = bar(1,2)  is also working fine with most compilers).

After 20 mins I stopped staring at the RCS code for the Block2Capsule and couldn't figure it out. The RCS quadblock from the CSM is working fine on the capsule though once attached ingame. Probably an incompatibility of the built-in Thrusters? Just a thought...

**Comment by jsolson** [comment]
I wonder if the rcs is shielded. Try it with the bay doors open.

**Comment by Meltdown19** [comment]
Oh wait I tried to control the RCS with the docking controls (H,N,I,K,J,L) instead the whole time. stupid me.

**Comment by Meltdown19** [comment]
The Thrust for all engines is not the same as in the original config file. For example the AgenaA should have 33kN, but ingame its Thrust went down to 11,975kN. This is for RSS installed.

**Comment by jsolson** [comment]
I saw that too (check out the centaur engines). RF displays sea level thrust on the pallet.
For Apollo the problem is two of the thrusters will be seen as inside the cargo bay. Open the doors and all 4 fire. Collateral damage from RF fixing the RCS thrusters firing under fairings thing.

**Comment by ForlornWinter** [comment]
Hi,

I've noticed a bug with the Augustus Gemini-derived automated resupply pod. 

When RealFuels is installed, the Augustus' "switch cargo" context menu function doesn't work. By default, it should have an empty tank for ore, which it does not have with RealFuels installed. Instead, the Augustus is filled with hydrazine. Attempting to switch to another cargo configuration using the context menu does not have any effect. A similar context menu function does work correctly on both the AARDV cargo resupply module and the MOS pressurized cargo segment. 

I'm running 1.3.1 with an extensive modlist, but I've verified that the issue is RealFuels related by uninstalling RealFuels and confirming that the part works as intended without it.

**Comment by jsolson** [comment]
It's probably the monoprop in that part throwing things off. Could you try this patch and see if it fixes it. I don't use RealFuels.

~~~
@PART[bluedog_Gemini_Resupply_Capsule]:First
{
    !RESOURCE[MonoPropellant] {}
}
~~~

I assume using the B9PartSwitcher for supply tanks is preferred to the RealFuels tank utility?

**Comment by ForlornWinter** [comment]
Yes, that did fix it. After seeing how simple it was to fix, I'm kicking myself that I bothered you instead of doing it on my own. As far as B9 being preferable to RealFuels-- I think it's a lot simpler to just use B9 instead of RealFuels for the supply parts (AARDV, Agena cargo box, MOS pressurized cargo segment, and the Augustus pod). RealFuels doesn't allow TAC-LS resources and ore (which is the "stock default" on these parts currently) in the same tank type, and it doesn't support USI-LS resources at all as far as I can tell.

**Comment by jsolson** [comment]
I think there's a global search and replace monoprop with hydrazine in the the stockalike configs that must be screwing things up. You could probably change it to hydrazine instead of deleting it. Multiply the amounts by 5 when doing that.
