### ISSUE TITLE
IMPROVEMENT: bluedog_LR87_SingleChamberB.cfg model issue

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#320]
When selecting the bare-engine option on the B9 part switch functionality a gap is left between the top node and the top of the engine.  I can hide this by using the part move tool but it is a pain to do this over and over.     I am using this engine on a probe lander and needed less height so chose the bare engine option for my 1.25m tank I was attaching it to.

**Comment by jsolson** [comment]
That would be the price for the convenience of one part / many modes. What you're looking at is the entire engine.

Keep in mind you're only getting this switcher because it's not terribly difficult to hide portions of the model. A second engine mesh located to line up with the attach node would I imagine be very inconvenient for the 3D modeler and would screw up engine effects. Moving or otherwise manipulating nodes wouldn't change anything. Once attached it won't move no matter what you do with nodes, so you'd still have to move it. @CobaltWolf may have ideas I'm not thinking of. This effect is 99% model magic.

The shroud sizes not changing with the mount size needs to be addressed if possible though. A 1.25m shroud on a 1.875m mount looks silly.

**Comment by CobaltWolf** [comment]
Allegedly B9PartSwitch can also change nodes
