### ISSUE TITLE
Fairing max sizes

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#330]
Some fairing bases have a max radius which seems out of line with similar fairings. Eg the fenris-625/stock 1.25m Fairing have a max radius of 1.5m, while the Promethus-I 1.5m fairing has a max radius of 0.94m, and the Promethus-II is even smaller at 0.8m.

And the Viklan .9375m to .675m adapter fairing has a max radius of 1m, while the plain Fenris .9375m fairing has only 0.75m max radius.

**Comment by jsolson** [comment]
~~~
Size	Max Radius
0.625	0.75
0.9375	1
1.25	1.5
1.5	1.5
1.875	2
2.5	3
3.125	3.25
3.75	6
5.625	6
~~~

Discrepencies:
Ablestar (0.9375) has a radius of 0.75. That can probably go up to 1m.
Titan I (1.5) has a radius of 0.9375. Not much over the base, that can go to 1.5m.
Titan II (1.7) has a radius of 0.8. This makes sense due to the design of the base. The fairing does not flare out.
SIVB and Skylab (3.75) have a radius of 3.5. Stock uses the absurdly large 6 meters. I think 3.5 is quite reasonable here, but we could bump it up.

Before anything gets changed, were any of these setup that way for a reason? Like the Titian II fairing.

**Comment by jsolson** [comment]
Updated. Close this in a few days if there's no objections/concerns.

**Comment by Rodg88** [comment]
Grabbed the updated version, much better. However I'd vote for allowing the Titan II to go bigger, for flexibility. Though I realize there's another 1.875 fairing available, so it's not much of a problem.

Also for the Titan II, the fairing base radius might be better as 0.85, and if it's still going to not flare out, the max radius should be 0.85 too, as the outer edge of the upper side of the fairing base is 1.7m wide. With 0.80 there's a small 90° lip around the fairing.
