### ISSUE TITLE
BALANCE: J-2-SL has lower SL thrust than J-2

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#384]
I think it's something to do with the 25% thrust for lifters, 50% thrust for upper stage balance. Honestly, I think just buff it so it's like 20-30 more thrust at SL. Thoughts?

**Comment by jsolson** [comment]
Get rid of the J-2-SL is my first instinct. This is a tough one to hand wave away.

We could cut the J-2, J-2S, and J-2A-2 sea level Isp in half. That would cut it's sea level thrust in half with minimal impact in flight since you're 90% or more of the way up the Isp curve at stage 2.

But then what do we do with the Toriodals.

Cutting the sea level Isp in half on a 50% thrust upper would bring it's sea level thrust down to 25% in line with lower stage balance, but it also would double fuel consumption off the ground.

**Comment by TJCizadlo** [comment]
Personally, I think the J-2SL should be kept, and probably get a buff, because it is an interesting engine, and I'd like to see it kept.

**Comment by jsolson** [comment]
This is what it looks like if we normalize the J-2 family in the middle at 37.5%.
````
Thrust current vac/sl -> 37.5% vac/sl
J-2-SL    218/180 -> 352/290
J-2       516/245 -> 388/184
J-2-T250K 555/365 -> 417/274

**Comment by CobaltWolf** [comment]
this pleases me

**Comment by Pappystein** [comment]
I will add, since I was one of the instagators for it that the specs in BDB for the J-2SL were developed by reverse engineering the MODEL and not anything from RW.  I agree with Cobalt that JSO's spec improve balance re bell J-2s.   But the J-2T is hardly in the same performance envelop.   As a TRUE toridal (not a plug) Aerospike, shouldn't the ISP/Thrust be nearly constant from SL-Vac?   You have almost a 50% increase in thrust.  or is it just ISP that I am thinking of?

**Comment by jsolson** [comment]
>this pleases me

No doubt the J-2-SL-OP will be popular. Lowering the thrust on the uppers may be a problem though. They were originally 25% and got bumped to 50% after testing.

@Pappystein the J-2T specs come from astronautix. Those are the Isp numbers they give.

**Comment by jsolson** [comment]
The buff for the SL engine is still pending

**Comment by CobaltWolf** [comment]
Alright, I mean are we good with it? Also, are the stats of the other J-2 variants (the part upgrades) properly adjusted?

**Comment by jsolson** [comment]
>the stats of the other J-2 variants

They are multipliers of the base part so everything's adjusted.
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/43c10543deed70fa6b7e50583d2094dd3285efb4/Gamedata/Bluedog_DB/Parts/Saturn/bluedog_J2.cfg#L191
