### ISSUE TITLE
NEW PARTS: RL10-A and RL10-B Variants

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#400]
- [x] RL10A-4 - Short extending nozzle, as seen on Atlas II and Atlas III
- [x] RL10B-2 - Large extending nozzle, as seen on Delta IV

- [x] Finish texturing - need some work on the mechanisms for the nozzles, nozzles are mostly done.
- [x] @jsolson investigate strange behavior and see if it can be eliminated.
- [x] fix autoshrouds

**Comment by CobaltWolf** [comment]
@jsolson can we see about making the animations work in the VAB? I'd like to ignore it, but 1) there's a button which seems to be non functional which will confuse users, and 2) you need to be able to test for clearance for clustering.

This is in addition to the issue I reported but have not been able to replicate. The biggest thing (to me) would be to see what sort of behavior the CryoEngines module has. It's been over a year since the module was integrated into BDB.

**Comment by jsolson** [comment]
Last I looked cryoengines retracts the nozzle when the engine is shutdown. We do not. Other differences are trivial.

Working on the editor.

**Comment by CobaltWolf** [comment]
Awesome, thanks. Let me know if you need a hand with anything.

**Comment by jsolson** [comment]
Commenting out the engine heat animation let the engine animation work in the editor. Fortunately Nertea had the solution. The heat and nozzle animations each had to be assigned a different layer (whatever that is).

I enabled inflight use of the animation (isOneShot), and set the engines to ignite at 25% extended rather than fully extended (WaitForAnimation). You can set WaitForAnimation to anything between >0 and 1. 1 is fully extended. Change those to get whatever effect you like.

ModuleBdbAnimatedEngine is a rewrite. Keep an eye on it.

**Comment by CobaltWolf** [comment]
Good stuff. Thanks man! I'll try and take a look at it tonight, but it is something of an occasion so it might have to wait until tomorrow.

**Comment by jsolson** [comment]
There's no textures on the shrouds. It's that fluorescent purple.

**Comment by CobaltWolf** [comment]
Thx will fix

**Comment by longlong2002** [comment]
RL10B-2 FOR DELTA III
