### ISSUE TITLE
IMPROVEMENT: S-II Interstage Colliders

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#401]
S-II Interstage still has very offset colliders, which can be disconcerting to new players.

**Comment by jsolson** [comment]
Might it be possible to make this interstage like the SIVB with the ullage motors included, and use a mesh switch for the 0, 4 or 8 motor variants? Can the thrust vectors be changed with the mesh?

**Comment by CobaltWolf** [comment]
Nope, trust me I ask Blowfish that about once a week on Discord. 😄 You can't access anything that is affected by other modules.

**Comment by jsolson** [comment]
What I'm asking is: Are the thrust vectors part of the mesh that's changing?

If mesh A has 4 thrust vectors named thrustVector, and mesh B has 8 thrust vectors also named thrustVector, would that work? You wouldn't be modifying ModuleEngines since the referenced thrust vector name doesn't change.

Maybe this makes no sense. Not a modeler.

My personal preference for the S-II interstage problem is to lose the standalone motors and make the most common configuration, 8 motor fairings with 4 of them firing. Slap it on and go.

**Comment by CobaltWolf** [comment]
The way I understand it, the thrustTransforms are compiled along with the rest of the part when the game is loaded. The transform itself cannot change, though I believe it can be moved.

**Comment by jsolson** [comment]
It occurs to me we can't put the motors on the interstage part anyway because of the way this part is staged. So disregard everything I posted here :-)

**Comment by jsolson** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/4b308a639a3a5e9b614ae5525d9564366022a4eb
