### ISSUE TITLE
BUG: New Atlas tanks have negative dry mass on all settings

### ISSUE THREAD

**Issue by iGGnite** [CobaltWolf/Bluedog-Design-Bureau#417]
When you launch a ship with Bossart-1-A5-500 Adapter Fuel Tank on it empty, the rocket stays and sticks in place because the Bossart-1-A5-500 Adapter Fuel Tank is somehow anchored in position and just starts spinning, easily repeatable by launchin a probe core with an empty Bossart-1-A5-500 Adapter Fuel Tank

**Comment by iGGnite** [comment]
It doesnt only happen with empty LH2/OX, I encountered this problem with with LF/OX and Monoprop aswell
![screenshot924](https://user-images.githubusercontent.com/36937528/36840151-514d2c44-1d44-11e8-9fdf-5860fe6490ee.png)

**Comment by jsolson** [comment]
You might have something else going on because I can't duplicate that. Only the LH2 goes negative. Did you try with the fix I uploaded a few hours ago?

**Comment by iGGnite** [comment]
I have SMURFF installed

**Comment by jsolson** [comment]
I see no change with SMURFF installed. We set the %SMURFFExclude = true flag. Are you doing something to override that?

**Comment by iGGnite** [comment]
No I'm not changing any of the files, these are my mods: 
![67062cbfe9eabd1c2a37a6dc85c1096f](https://user-images.githubusercontent.com/36937528/36899750-c8effbdc-1e20-11e8-8f1a-6ab27e1c10ac.png)

**Comment by jsolson** [comment]
Ok. Need to see your ksp.log and ModuleManager.ConfigCache.

**Comment by iGGnite** [comment]
[github bdb logs.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/1775247/github.bdb.logs.zip)

**Comment by jsolson** [comment]
Grab [this file](https://raw.githubusercontent.com/CobaltWolf/Bluedog-Design-Bureau/master/Gamedata/Bluedog_DB/Compatibility/B9PartSwitch/B9PartSwitchTanks.cfg) and replace the file in GameData/Bluedog_DB/Compatability/B9PartSwitch with that one. It won't break saves. You should see the Balloon tank type replace LFO on the Atlas tanks, and the dry masses will be positive.

SMURFF nor anything else is interfering. Your 10x system scale is pushing masses down to extremes so the effect of the bug is much more pronounced, giving you worse negative masses than I was seeing.

**Comment by iGGnite** [comment]
Your file fixed all the masses, thanks for your effort. If I come across anything else I'll let you know.
