### ISSUE TITLE
KIS Compatibility

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#62]
Need to add KIS compatibility to make the Resupply parts for MOS worthwhile.

Parts that need it:
- [ ] Mercury capsule
- [ ] Agena Resupply Container
- [ ] Gemini Resupply Capsule
- [ ] TRAILS Gemini capsule?
- [ ] Transtage pressurized compartment
- [ ] MOS airlock module
- [ ] MOS warehouse module

**Comment by CobaltWolf** [comment]
Someone needs to look at this.

**Comment by Cowboy-WY** [comment]
Which part is Transtage pressurized compartment?

Also any other parts other than listed below?

Looks like I just need a few numbers for each of these parts assuming all will be both internal and external access.  A few already have them in the .cfg



									maxVolume	slotsX	slotsY
bluedog_mercuryPod
bluedog_Agena_ResupplyContainer - 		2000		        4		4
bluedog_Gemini_Resupply_Capsule - 		6000		        5		5
bluedog_Gemini_Crew_A
bluedog_Gemini_Crew_B
bluedog_MOL_KISmodule -                                 8000		        8		5
bluedog_MOL_UnpressurizedCargo
bluedog_MOL_Airlock

**Comment by CobaltWolf** [comment]
The Transtage pressurized compartment had transitioned into the bluedog_MOL_KISModule by the time it was put in game. I'm not sure if there's anything else, other than Apollo/LEM obviously. The LEM will not have extra KIS storage for the experiments, that's covered in my other mod.

**Comment by Cowboy-WY** [comment]
I f you have the numbers for the parts listed above, I can get them updated.

Do you want this in the part config files?  Or in a separate KIS.cfg for module manager?

**Comment by CobaltWolf** [comment]
I don't have any numbers. I don't know what the volumes are. Is it possible to find the ratios for the stock KIS stuff?

**Comment by Cowboy-WY** [comment]
Based on what KIS uses for parts.

Roughly 1000 liters per cubic meter for storage parts (imagine that) and it also adds 300 liters per crew member by default.  Based on this I wouldn't add anything extra for the crew pods and use the following:

bluedog_Agena_ResupplyContainer - 700 3x3
bluedog_Gemini_Resupply_Capsule - 1250 4x4
bluedog_MOL_KISmodule - 3000 4x4
bluedog_MOL_UnpressurizedCargo - 0 - I'd use it for placing actual parts because it opens up
bluedog_MOL_Airlock - 300 2x2


I'll try putting it in a separate config file for module manager instead of in the parts themselves.  This will make it easier to see what parts have this in the future.

**Comment by CobaltWolf** [comment]
You mean removing it from the parts that have it in their part.cfg? Good call. I don't use KIS that much but that all sounds good to me. 

-----Original Message-----

**Comment by Cowboy-WY** [comment]
Completed in #143

**Comment by CobaltWolf** [comment]
@Cowboy-WY Awesome.
