### ISSUE TITLE
Tech tree placement for new parts

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#620]
Tech tree needs to be evaluated so parts can get placed:
Gemini Lander
Gemini station parts
LDC Titan
Helios
The new probe bits
New Gemini bits
The new Titan parts
Atlas SLV-3X
The new part upgrades probably also need to get checked

**Comment by Pappystein** [comment]
I am working on some thoughts for this but others should feel free to jump in.

Sadly I think we run out of room too quickly in the Stock tech tree.   I am also looking at placement for Nertea's community tech tree even thought it is not my first choice.

**Comment by DeltaDizzy** [comment]
I had briefly considered a "stockalike" version of CWPT, one that is tailored more towards gameplay rather than historical order. It would keep the techtag system and most of the nodes, but would simply move them around/rename them/maybe adjust unlock requirements. It should have plenty of room, with ~100 more nodes than the stock tree.

**Comment by friznit** [comment]
Spreadsheeted the BDB parts into a stock tech tree layout for reference.  It's open to edit.

https://docs.google.com/spreadsheets/d/14xRVA3dYH2K2nRoGR0tMfzwuzAzqxoM1lc-1-MRkNKI/edit?usp=sharing

**Comment by longlong2002** [comment]
before release BDBv1.6.0 should double check anything but bug
