### ISSUE TITLE
Real names patch bugs

### ISSUE THREAD

**Issue by birdog357** [CobaltWolf/Bluedog-Design-Bureau#668]
The following parts are not affected by the real names patch:
-All Skylab except the WWS that is a basic tank texture
-Modified Saturn tank parts from the extras patch
BSA-0050-0000 - Viklun-40 SA
BSA-0100-0000 - Fenris-62 SA
BSA-0100-0000 - Rosuette-6SA (Should one of these have a different part number?)
BSA-0100-0050 - Fenris-80 SA
BSA-0120-0100 - Fenris-100 SA
BSF-0120 - Fenris-BT Engine Fairing
Dioscuri-1 SRB
Etoh-1400 LF Tank
Etoh-400 LF Tank
Etoh-CS
Fenris 1.25 Stack Decoupler
Vinklun 0.625 Decoupler
Fenris 0.9375 Decoupler
Fenris 180 LF Tank
Fenris fairing base
Viklun-100 LF Tank
Viklun-4688 Fairing base
Viklun-60 LF tank
Centaur-D1800 Fuel tank has Centaur misspelled.
Viklun-800 LF Tank
Viklun-3125 Fairing Base
Viklun-UKSK Engine
The entire Diamant/Rosuette Line (to be deleted from BDB?)
Prometheus-II 1.25 SA(Deprecated?)
Prometheus-II 1.5 SA(Deprecated?)
Entire Fenris line(Type Thor into seach)

**Comment by zorg2044** [comment]
I think your BDB dev install isnt quite up to date. I've corrected the Centaur misspelling but just about everything else has realnames now I think. Diamant is due to be deprecated. 

For saturn I expect you mean the MLV and INT patches? Those were done by Pappystein, I expect he will update the realnames as he did for the HLG stuff when he has the time. Im not familiar with the content myself.
