### ISSUE TITLE
Updated Craft Files for Rel 1.61

### ISSUE THREAD

**Issue by friznit** [CobaltWolf/Bluedog-Design-Bureau#681]
I'm tidying up a limited collection of craft files providing a spread of canon rockets documented on the wiki.  Typically aiming to provide a craft file for the most complex builds based on the principle that you can strip bits off it to make the easier ones.

- [x] Scout (Scout A)
- [x] Viklun (Vanguard)
- [x] Etoh (Jupiter C & Mercury-Redstone)
- [x] Chryslus (Juno IVB)
- [x] Paxus (Peacekeeper)
- [x] Pulgasari (Minotaur V)
- [x] Minerva (Athena IIc)
- [x] Fenris (Thor Able, Thor Agena & Thorad Agena)
- [x] Daleth (Delta 1000, Delta II-7925, Delta III-8930)
- [x] Bossart (Atlas LV-3, SLV-3, Atlas I, IIAS, IIIB, Atlas 3K, 3X, CELV)
- [x] Prometheus (Titan I, Titan II(23)G, GLV, Titan IIIA, 34B, IIIC, IIIE, CT-3, IVB)
- [x] Muo (Atlas V 451 & 552)
- [x] Herakles (Titan 3L2)
- [x] Sarnus (Saturn I & IB Apollo, Saturn V, Saturn II INT-18, Saturn MLV 20 & 21, ETS IC & H02)

**Comment by zorg2044** [comment]
I think it would be good to add a CELV build as well. Er Gem 60 XL for the boosters I guess?

Ed kyle described the proposed boosters as having almost as much prop as an AJ60, the GEM 60XL fits that bill and looks similar to the drawing.

**Comment by friznit** [comment]
[Craft Files.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/3775890/Craft.Files.zip)

All done as above.  Would be good to sanity check if you get a moment.

**Comment by zorg2044** [comment]
Atlas II AS craft seems to have universal storage ACD so it doesnt load on a clean install.

I havent done it myself yet but due to the low positioning of the CELV booster decouplers, it may need to be flight tested and some sep motors added to the booster nose. Maybe the titan 2 2nd stage retro motor.

For the Atlases would also be sensible to select the correct the LR89 B9 config. It might produce a warning if trying to load earlier (not sure but also for correctness sake I guess)?

I think the craft files need to be sanitised for extraneous modules by loading and resaving on a clean install with only BDB and its dependencies too. So it doesnt contain unneeded modules like mechjeb and decoupler shroud. The craft load fine but it gives an error message while doing so and can induce panic in beginner players :P

No rush on this, already made a small bug fix release and theres nothing urgent pending right now for 1.6.x

**Comment by friznit** [comment]
[BDBCraftFiles.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/3795353/BDBCraftFiles.zip)

All scrubbed up and flight tested on a vanilla install.
