### ISSUE TITLE
Real names config is missing some BDB_extras parts

### ISSUE THREAD

**Issue by IronKerbal** [CobaltWolf/Bluedog-Design-Bureau#702]
Some of the parts from BDB_Extras are missing real names.

**Comment by zorg2044** [comment]
Parts added in to the game by BDB extras are maintained by whoever added them to begin with. I believe most of them were by Pappystein and he has updated some of them. If theres some missing do feel free to make a pull request targeting the 1.6 hotfixes branch.

**Comment by Pappystein** [comment]
I have sent Zorg a corrected Realnames code...  That he is going to further update it to further reduce the errors the move of BDB_RealNames caused.   Most of the missing parts are due to the parts having :NEEDS[BDB_RealNames] which was fine when RealNames was it's own directory... Not when it is in the BDB_Extras folder.
I have already created a PR to fix my parts to go with this.

**Comment by zorg2044** [comment]
Yup so no special handling is needed anymore, realnames patching now takes place at :FOR[zzzBluedog_DB]. So a +PART copy that even runs :AFTER[Bluedog_DB] will still be patched by realnames later in the MM patch order.

**Comment by Pappystein** [comment]
Awesome and thanks!
