### ISSUE TITLE
Realplumes still sometimes break stock fx

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#74]
Not sure HOW this is happening, since it all worked on my end without RP...

**Comment by VenomousRequiem** [comment]
It should work fine? We fixed this twice before, i blame CKAN.

**Comment by CobaltWolf** [comment]
When in doubt, blame CKAN

**Comment by jsolson** [comment]
I can not reproduce this. It's probably a partially uninstalled RealPlume and/or Smokescreen that caused the recent posters problem. Just having an empty RealPlume folder is enough for a NEEDS[RealPlume] test to be true. CKAN uninstalls have been known to do that.

A little trick occurred to me. We can test for NEEDS[zRealPlume,SmokeScreen] instead of NEEDS[RealPlume,SmokeScreen]. The zRealPlume will only pass if the RealPlume configs are acually running.

**Comment by CobaltWolf** [comment]
How does that work?

**Comment by jsolson** [comment]
How does what work?

**Comment by CobaltWolf** [comment]
Like how does that make it work only if the RP configs are actually running?

**Comment by jsolson** [comment]
The zRealPlumes is created by the configs. It won't exist if it's just an empty directory fouling things up.

I'm thinking the best solution might be for Venom to donate the configs to the [RealPlume Stock Configs](http://forum.kerbalspaceprogram.com/index.php?/topic/130576-112-realplume-stock-configs-continued-v0107-252016/)

**Comment by CobaltWolf** [comment]
He has a git hub. We could just do a pull request. 

-----Original Message-----

**Comment by VenomousRequiem** [comment]
No, it's easier for me to update and keep track of them if i do them myself here on our own Git.

**Comment by CobaltWolf** [comment]
I was kind of thinking the same thing

**Comment by jsolson** [comment]
For now we'll call this not our issue. If it comes up again try to pry a ksp.log out of them. Sgt.Shutesie's delete the plumes folder fix will suffice otherwise.

**Comment by CobaltWolf** [comment]
aight. Should we close it?
