### ISSUE TITLE
Nimbus tracking solar panels lose mirroring if moved after first placement in VAB

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#821]
Relating to Nimbus panels

**Comment by jsolson** [comment]
What I'm seeing is, they lose mirroring and get totally screwed up after extending and retracting them in the VAB.

**Comment by jsolson** [comment]
After a Left or "B" side panel extends and retracts in the vab, it rotates 180 degrees its pivot and remains that way until the vessel reloaded/launched. I suspect the problem is ModuleDeployableSolarPanel not expecting it's parameters to change after OnStart.

Setting both pivots in the cfg to the Right or "A" side pivot eliminates the visual issue in the VAB, but then the Left/"B" side panel does not track in flight.

Changing the code to not update ModuleDeployableSolarPanel in the VAB seems to have cured the problem.

![Untitled](https://user-images.githubusercontent.com/16825376/74586670-e18dd680-4fb7-11ea-9164-4e5cef28196a.png)

**Comment by zorg2044** [comment]
This seems resolved.
