### ISSUE TITLE
Look at reusablity on science cameras

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#88]
[post](http://forum.kerbalspaceprogram.com/index.php?/topic/122020-112-bluedog-design-bureau-massive-stockalike-parts-pack-v0105-krikkit-may1616/&page=126#comment-2608291)

Should be no limit on digital. All should be resettable by a scientist.

**Comment by CobaltWolf** [comment]
Lo-Tech camera: Lightest - just a simple lens, aperture, film roll etc. Can take 4 (6?) images before needing to be reset by a scientist. Must have its data returned - difficult / not fun without being able to have little return capsules ala Corona.

Mid-Tech camera: Medium weight. In addition to the camera you're carrying equipment to develop and scan the film. Can return low quality (50%) images, and can take 6 (10?) images before having to be refilled - it still uses a finite amount of film. 

Hi-Tech camera: Heaviest + expensive. You're paying for convenience and capability. Can take unlimited # of pictures, and transmit at 100%. 

DMagic is really good about updating his plugin- usually within a week, even a couple days, if something's wrong. If there is strange behaviors try and narrow them down and I'll let him know.

We need more sciencedefs. The cameras should have one for pretty much every effing biome.

**Comment by CobaltWolf** [comment]
@jsolson how is this going?

**Comment by rasta013** [comment]
OK - took it upon myself to go in and review these before diving into the definitions which is next.  Currently, I' have the low tech camera staying exactly the way it is already.  .01 for mass and limited to 4 images.  The mid-tech camera I've bumped to a mass of .035 (change of .005) and max images to 6.  

The high tech camera I'm treating as a separate beast.  I cannot see any way to justify another increase in mass because a digital camera is always going to be lighter than any kind of film system.  There is no development process and the camera and storage essentially represents a CCD and hard drive for data storage.  There is just no way to explain how this system can be heavier.  With that in mind though, my suggestion would be to bump the tech node one more level.  It is currently sitting at ScienceTech which is a 300 point node so the part would be available with only one R&D upgrade.  by moving it to AdvancedScienceTech it now requires 550 science points as well as the 3rd level of the R&D building.  I honestly think this is enough justification to bring the weight down instead of up.  With all this in mind I've set the mass at .025 and the images as unlimited.  To me this seems like a fair trade between cost/accessibility of the part and ease and convenience you are rewarded by getting to it.

Thoughts?

**Comment by jsolson** [comment]
The idea I have floating around my head is to have a single upgradeable
camera rather than three that basically become obsolete as newer models are
unlocked.

I'd also like to dispense with multiple results per part since that's not
how ksp works, and instead go with film rolls that each can contain a
result, and are convenient to recover.

**Comment by rasta013** [comment]
I love that idea actually.  An upgradeable part would be an even better solution.  Are you able to code the plug-in to handle that?  As far as I know it'll require that to be able to upgrade through the tech tree similar to how MechJeb and a few other more obscure mods do it.  That was actually the reason why I was headed along the path that I suggested above since I know nothing about coding unfortunately. :(

**Comment by jsolson** [comment]
I can code it. I have a working prototype using the required camera/film roll modules. Internally the film rolls contain a custom science experiment module that requires the camera to be present on the craft and will inherit the camera experiments properties. They otherwise function like a normal experiment. I'm using the 0.625 battery as a stand in for the model. Combined with a rescaled heatshield and parachute, and the probe core of your choice they make wonderful return vehicles. The little "Wally" srb makes a great retro motor for deorbiting.

Upgrading MechJeb style is one route, but it has gottchas. Like how do we handle craft already in flight when the upgrade comes. I was thinking of doing it with parts instead. For instance:

A High Resolution Imaging unit, that increases the science return per result. I have code that can do this. What we'd actually do is cut the science return on the base camera in half, this part would bring it up to full value.

A Photographic Transmission unit, that allows transmission of results.

A Digital Image Processor, that makes the camera infinitely reusable without a scientist or lab.

Having any of these parts present on the craft would upgrade the camera. I haven't fully thought this through but that the basic idea.

**Comment by rasta013** [comment]
That's a seriously good idea man!  I really dig it.  I do see what you mean about the MJ style upgrade though since it would upgrade craft in flight.  The add-on unit process is a much, much better solution and avoids that situations entirely - good thinking.

So a combined question for you then - how close do you think you are to being able to implement the code at least to a testing stage and what do you think about offering the intermediate stand-in process I've suggested above if you think it's going to be a while longer?  If you think it might be a bit before testing can begin then at least the above changes would get something to the players to help balance the cameras in the short term is my thinking.

**Comment by jsolson** [comment]
Go for it, I haven't heard any objections. Hard to say how long things will take. We lack a consensus, and would need models for parts. I'm not the model maker.

Another idea that has been floated is to have the camera consume a film resource and limit the number of results that way. CW has expressed concerns about that path though.

**Comment by rasta013** [comment]
I think the resource consumption idea would actually work nicely combined with a plug-in like you're aiming at.  That would expose the resource to configuration abilities via MM for enhanced part configs.  Also, by defining it as a CRP controlled resource it would allow things like volume and mass definitions to be exposed as well making it a lot more flexible.  

That said, I agree with CW as it stands right now though.  I think doing that without the plug-in to back up the entire system would make it needlessly complex in the short term.  As individual parts controlled via DM's ScienceAnimate it makes it easier to keep it balanced as a temporary filler.

The more I think about your idea though the more I'm really liking it a lot.  Can't wait to see what you get pulled together! :smile:
