### ISSUE TITLE
SUGGESTION: Add Dependency

### ISSUE THREAD

**Issue by 7ranceaddic7** [CobaltWolf/Bluedog-Design-Bureau#922]
ModuleSimpleAdjustableFairing is a use in the SUBTYPE[] node.

Without the mod Simple Adjustable Fairings installed, B9 throws EXC errors.

Suggest adding SAF as a dependency in CKAN.

https://forum.kerbalspaceprogram.com/index.php?/topic/122020-181173-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v162-%D1%82%D0%B8%D1%82%D0%B0%D0%BD-24nov2019/&do=findComment&comment=3814577

**Comment by zorg2044** [comment]
If you have BDB parts with the SAF module that means you must be using the Development branch. Since SAF is not a dependency for the current BDB 1.6 release our netkan will only be updated once BDB 1.7 is out of dev and released. If using the dev branch it is suggested to check the bundled dependencies (which are kept up to date in the github folder).

**Comment by 7ranceaddic7** [comment]
Yeah, my bad.
