### ISSUE TITLE
SCANSAT v20+ rebalance

### ISSUE THREAD

**Issue by thunder175** [CobaltWolf/Bluedog-Design-Bureau#934]
Could someone please double-check the sensor types in the SCANSAT integration patch? I've noticed that at the low tech levels the MV-4 Mufar and Burke-2 TV cameras are listed as biome scanners. I'm not sure if this should be the case. Shouldn't these be SCANSAT low resolution visual scanners instead of biome? If left as is the balance seems significant off since you don't get access to the hyperspectral scanner to do biome scanning till later in the tech tree.

**Comment by zorg2044** [comment]
Done, still need to figure out what to do about the resource scanners since I believe SCANsat v20 has removed individual resource scan types in favour of a unified resource scanner only? This throws the balance off since many are early  game (magnetometers and such) but could be seen as balanced before since they could only detect one resource. If anyone has any suggestions I'm open.

**Comment by SilveiraMarcel** [comment]
I think we could remove the ModuleSCANresourceScanner from the resource scanners, leaving only the SCANresourceDisplay module. This way they can be used to read the amount of resources. Other option is to remove both modules and use the CRP patch.
I'm working on the second option right now (replace scansat with CRP module)

**Comment by zorg2044** [comment]
Hmm ok that sounds reasonable, a full fledged all resource scansat module on a lot of those would be too OP.

**Comment by CobaltWolf** [comment]
Did this get taken care of?

**Comment by zorg2044** [comment]
Not the resource part yet.

**Comment by Laurentyb** [comment]
Another way of tackling it is the create low and high alitmeter scanners, so early game your scan arc is very small for things like ore scanning. Happy to take a swing at it if its not being worked on already.

**Comment by stanirya** [comment]
There's also another potential issue: BDB parts provide easily accessible AnomalyDetail (BTDT) scanners that scan from orbit (early parts from 20km, later parts 100km+). In "vanilla" SCANsat you can only scan AnomalyDetail when you are next to an anomaly (like 1-2km away). I can maybe see how this could possibly potentially make sense on a part like the SG-10 / MOL (seeing as it's basically a big manned orbital SIGINT military lab) but for other parts this feels almost like cheating.

**Comment by Grimmas** [comment]
Some of the AnomalyDetail scanners in BDB are way overpowered. Not sure if this was intentional or not. 

The BTDT scanner in SCANsat only scans AnomalyDetail from 2km height (which is actually also an issue in itself because it seems to count from sea level so anomalies above 2km don't get scanned). 

In BDB, some parts can scan AnomalyDetail from up to 500km orbit. I can maybe somehow see this as justified on huge parts like the MOL, as you could totally launch a MOL to collect this kind of data, but not really on the other, smaller parts.

A few of the other scanner modules (visual, biome, etc) are also configured in a much more relaxed manner compared to their SCANsat counterparts.

**Comment by zorg2044** [comment]
none of the authors are experts on scansat balance. If you have any suggestions to change the balance please make a PR with a brief description of what changes you're proposing and why and we will be happy to merge them.
