### ISSUE TITLE
Saturn S1 engine mount symmetry 

### ISSUE THREAD

**Issue by VenomousRequiem** [CobaltWolf/Bluedog-Design-Bureau#95]
The engine mount for the Saturn 1 first stage's symmetry isn't responding as intended. Try and connect two different kinds of engines to the bottom; you'll see what i mean.

**Comment by CobaltWolf** [comment]
@jsolson is it possible to have more than one 'stackSymmetry' definition? Otherwise I don't think there's an easy way around this. :/

**Comment by jsolson** [comment]
Change 7 to 3
On Jun 8, 2016 9:39 AM, "Matthew Mlodzienski" <notifications@github.com>
wrote:

@jsolson <https://github.com/jsolson> is it possible to have more than one
'stackSymmetry' definition? Otherwise I don't think there's an easy way
around this. :/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/95#issuecomment-224591579>,
or mute the thread
<https://github.com/notifications/unsubscribe/AQC8IJ3w-iLXAQDgwl9CwWlOKskg27A2ks5qJsYfgaJpZM4Iwi0j>
.

**Comment by CobaltWolf** [comment]
Oi you're supposed to be asleep

**Comment by jsolson** [comment]
I keep forgetting to tags my commits.
[link](https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/9bfed32329c6a003546e1f8449765721d872b02c)
