### ISSUE TITLE
Bluedog_DB\Compatibility\B9PartSwitch\B9PartSwitchTanks.cfg adds MonoPropellant to any B9 subtype

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#957]
This patch:
in Master 
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/ae63de73b7476c5ca12ce800cb4cf04787f17e40/Gamedata/Bluedog_DB/Compatibility/B9PartSwitch/B9PartSwitchTanks.cfg#L315
in 1.7.0-Dev
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/d708a2cbdbd2c5b0ccc33548074843e458a7dee8/Gamedata/Bluedog_DB/Compatibility/B9PartSwitch/B9PartSwitchTanks.cfg#L377

adds the resource MonoPropellant to each B9 subtype it finds.

The result looks like this in MM cache:
```
		MODULE
		{
			name = ModuleB9PartSwitch
			moduleID = fuelSwitch
			switcherDescription = Fuel
			baseVolume = 1320
			SUBTYPE
			{
				name = LF/O
				tankType = bdbLFOX
				addedMass = -0.825
				addedCost = -1649.88
				percentFilled = 100
				RESOURCE
				{
					name = MonoPropellant
					unitsPerVolume = 0.189393939393939
					percentFilled = 40
				}
			}
			SUBTYPE
			{
				name = LH2/O
				tankType = bdbLH2O
				addedMass = -0.825
				addedCost = -1649.88
				percentFilled = 100
				RESOURCE
				{
					name = MonoPropellant
					unitsPerVolume = 0.189393939393939
					percentFilled = 40
				}
			}
			SUBTYPE
			{
				name = LH2
				tankType = bdbLH2
				addedMass = -0.825
				addedCost = -1649.88
				percentFilled = 100
				RESOURCE
				{
					name = MonoPropellant
					unitsPerVolume = 0.189393939393939
					percentFilled = 40
				}
			}
			SUBTYPE
			{
				name = MonoProp
				tankType = bdbMonoProp
				addedMass = -0.825
				addedCost = -1649.88
				percentFilled = 100
				RESOURCE
				{
					name = MonoPropellant
					unitsPerVolume = 1.18939393939394
					percentFilled = 40
				}
			}

```

**Comment by Gordon-Dry** [comment]
I guess adding a simple :HAS[#tankType[bdbMonoProp]] to the @SUBTYPE,* should be enough?

**Comment by jsolson** [comment]
The syntax of your patches appears invalid. `:HAS[#tankType[bdbMonoProp]]` combined with an index specifier `,*` does not work in MM. You have to use one or the other. Besides ugly non whole numbers in the cache, what problem are you trying to fix?

It is the way it is because a part may have 100 LFO, and 20 MP. That means the all MP fuel type has a total volume of 120 MP. The MP needs to be added to the LFO/Cryo,etc types because if the MP is not specified the 20 MP will be deleted since it's not included in the fuel type. The weird unitsPerVolume numbers maintain the 120 total volume of the part (100 fuel+20MP, or 120 MP).

**Comment by Gordon-Dry** [comment]
Well, if it's intended that a tank with the name LH2/O gets MonoPropellant added then I close this.

**Comment by jsolson** [comment]
It is intended.

This patch should only be triggered on the few parts with fuel+monoprop (originally the service modules, but now we have parts like Able with built in rcs+mp). If your seeing something on pure fuel parts there's an issue.
