### ISSUE TITLE
Ranger battery missing from latest version update

### ISSUE THREAD

**Issue by nally85** [CobaltWolf/Bluedog-Design-Bureau#970]
Hi,

Love your mod. But in the recent update the ranger battery is missing. I have used it on basically all my spacecraft. 

Which means none of my craft load in KSP. Is this a permanent change or has it just been missed?  

I can revert back to the older version and remove the battery from all my craft and relaunch them, but as you can imagine this would take a lot of time. 

But if you intent to add back in I can wait. 

Many thanks and kind regards

**Comment by zorg2044** [comment]
The old ranger battery has been soft deprecated (since there's a brand new one), meaning it should be hidden in the VAB but not actually deleted from the game. Im looking into why this is happening. 

However its also worth pointing out as the forum release post stated, you should treat a major BDB update as a save breaking change and should backup your saves before updating and ideally retire old craft before upgrading if not doing a new save entirely.

But we are looking into the issue as this is a bug.

**Comment by nally85** [comment]
Thanks, it’s been a while since I played KSP so still getting back up to speed with it. So should the old one I have just be replaced with the new one?

If not, I guess best thing to do is try and remove the part via the craft file. Keep up the great work as the mods awesome.

**Comment by zorg2044** [comment]
We've found the bug and will be releasing a bug fix update. However you should retire any craft using such parts as soon as possible. They will be permanently deleted in some future update (deliberately this time :P )

https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/8630c6f1a8e7c0ef8ac3b5093c8215c15a7f0037
