### ISSUE TITLE
Atlas

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#974]
### Classic Atlas Revamp

LR89
- [x] MA-1
- [x] MA-3 (fully independent)
- [x] RS-56 OBA

LR105
- [x] MA-1 (unaspirated)
- [x] MA-2 aspirated, angle joint for exhaust pipe
- [x] MA-3 

LR101
- [x] radial LR101 with optional cover
- [x] in line LR101

RD-180
- [x] Bare version plus ring mount
- [x] Atlas III boattail plus generic version without pipe
- [x] Atlas V boattail plus generic version without pipe
- [x] standalone 2.5m mount
- [x] standalone 1.875m mount

New booster skirt
- [x] Atlas A,B,C
- [x] Atlas D (default, most common)
- [x] Atlas II-B version with center blocked up
- [x] Atlas E/F

New Core tank mesh variations (there will be texture variations for unique paint schemes)
- [x] Atlas A,B,C (Textures: Silver A red trim '57 | B&W A '57,'58 | Silver B red trim | Atlas 10B SCORE | Silver C )
- [x] Atlas D (Textures: base silver, 
- [x] SLV-3A
- [x] Atlas E/F
- [x] Atlas G/I/II
- [x] Atlas III

Aft tank
- [x] default aft adapter tank
- [x] H1D Fatlas adapter tank

1.875m Conical Extension tanks (top diameter x length)
- [x] 0.9375x2.6m ( Atlas Able, SCORE, ICBM, Atlas Agena
- [x] 1.25x3.63m (Mercury, SAMOS, MIDAS)
- [x] 1.25x1.625m (Atas F OV-1, Atlas F MSD )
- [x] ~~1.25x1.31m (Atlas H MSD )~~
- [x] 1.5m Fictional

Cylindrical Extension Tanks
- [x] 1.17m (SLV-3B agena, Atlas F Agena Seasat, LV-3 Centaur AC-1 to Ac5)
- [x] 1.82m (SLV-3A Agena)
- [x] 1.96m (SLV-3C Centaur D, Atlas H)
- [x] 3.23m (Atlas I)
- [x] 4.19 (J1A/J-2 Japanese Atlas derivative)
- [x] 4.92m (Atlas II)
- [x] 7.39m (Atlas III)

SLV-3X and early 5 engine atlas
- [x] SLV-3X core tank
- [x] SLV-3X lower adapter tank
- [x] SLV-3X upper adapter tank (1.875m for SLV3x and long 0.9375 for 5 engine atlas)
- [x] 2.5m extension tank with length variants
- [x] 2.5m 5 engine mount (early 1954 atlas design)
- [x] 2.5m aft engine mount (for 5 engine design)

Rework CELV parts.
- [x] New cylindrical tanks. Consolidate variants into B9PS switch
- [x] New 2.5 and 1.875m conical tanks. Consolidate variants in B9PS switch.
- [x] New core tank
- [x] Refresh skirt textures
- [x] Refresh aft tank textures

OV1

- [x]  OV1-1 Probe
- [x] OV1-10 Probe
- [x] OV1-10 Magnetometer
- [x] OV1-10 X-ray spectrometer
- [x] OV1-10 Lyman Alpha photometer
- [x] Atlas Retained Structure side mount pod
- [x] Nose mounted dual ARS
- [x] 1.25m structural adapter (black and white)
- [x] OV1 fairing dual and tri decoupler

fairings [See SAF issue]
- [x] 1.25m MSD fairing
- [x] OV1 1.25m SAF fairing

Payloads

- [x] Atlas A nose cone (probe core)
- [x] SCORE nose cone
- [x] Side mounted scientific passenger pod

Other stuff

- [x] Atlas H 1.875m to 1.25m structural adapter to replace removed (incorrect) fuel tank part
- [x] Atlas Centaur retro motor
- [x] Clustered Atlas Booster system (1.875m Tri-Coupler to 1.875m upper stage adapter)
- [x] Atlas F command antenna

Japanese derivatives

- [x] NK-33 mount for J-1A (1x, 2x, 3x and 4x variants plus optional shroud extensions in 2 lengths)

paint variants
- [x] SAMOS
- [x] Seasat

Extra features
- [x] Auto jetisson of skirt at specified G

### Atlas V Revamp

- [x] Atlas V CCB (split into two tanks as it is now)
- [x] fresh tank texture variant
- [x] Length switches for CCB upper tank?
- [x] HLV decouplers
- [x] HLV nose cone
- [x] AJ-60
- [x] GEM-63
- [x] GEM-63 XL (bonus item)
- [x] SRB decoupler
- [x] 5xx fairing base
- [x] Internal Centaur interstage conical adapter for 5xx fairing base
- [x] 4xx Centaur adapter (Invaderchaos)
- [x] Centaur FLR? (TBD)
- [x] 500 series fairing texture refresh
- [x] Star 5F retro motor retexture

new PBR Textures
- [x] Balloon tanks
- [x] Atlas V
- [x] Engines

**Comment by GoldForest383** [comment]
Could we get:
OV-1 Satellite
OV-1 Tank Side mount
OV-1x2 Payload Adapter (As mentioned)
OV-1x3 Payload Adapter

http://www.spacelaunchreport.com/atlas-ov1.jpg

**Comment by CobaltWolf** [comment]
@zorg2044 feel free to do whatever you want with the Atlas parts - I trust you :) If you think you need to adjust the way the metal is done (or, dare I say...) go for it. Let me know what assets you need. Some thoughts / additions I'd like below:

L2 is going to be a gold mine for all this stuff. Do you still have a subscription? 

Something I definitely think we need - Atlas E/F side pods as a variant for the "main" tank. This is the one with the big bulge on the longer (?) pod.

![15b380388e04e593e4311f6d9618963b](https://user-images.githubusercontent.com/16356162/98302189-f79a5780-1f89-11eb-9396-4ac3cf29a6f7.jpg)



Another "must-have" for this - a 4x booster skirt like the original full sized Atlas design had. It's definitely doable at 2.5m in KSP (don't get too attached to this drawing - I just mean the general concept). It will also likely need a different adapter tank to connect the "main" SLV-3X tank to the sustainer tank. 

![image](https://user-images.githubusercontent.com/16356162/98301679-282dc180-1f89-11eb-9ae6-bc69a53bbc05.png)


I'd still like to see a solution for the LH2 vent pipe

![DF-SC-99-00074_cropped_and_rotated](https://user-images.githubusercontent.com/16356162/98302682-db4aea80-1f8a-11eb-833d-185a1a4c334d.jpeg)


If Invaderchaos is making more DMSP sats and such, we need to have solutions for the military surplus Atlas variants like Atlas H. 

![image](https://user-images.githubusercontent.com/16356162/98302854-2a911b00-1f8b-11eb-8dd5-adbdcf43a2d0.png)
![Atlas-H](https://user-images.githubusercontent.com/16356162/98302861-2c5ade80-1f8b-11eb-8359-787e88e33b3b.jpg)

And as an aside to you and the rest of the crew ( @jsolson  @blowfishpro @Invaderchaos ) - if we want, you can be doing point releases to push out your projects independent of the main releases (ie Saturn/Apollo). Probably would be a good way to keep things going now that we have multiple artists. My question is - what is the deal with working on branches? Because I feel like that would be a *lot* easier to manage for pushing out multiple streams of content?

**Comment by zorg2044** [comment]
@CobaltWolf My L2 has lapsed but I will be renewing. I totally forgot we already talked about MSD earlier (fairing and adapter). Anyway yeah definitely put that back on the pile, perhaps even the altair acs kit. 

Re metal I imitated the atlas textures for the peacekeeper fairing and I gotta say I was quite happy with it. I can look at tweaking it a bit though.

Re files I could use the FBX for 1.875 and 2.5m parts together with the all the PSDs for the 1.875m parts at least.

**Comment by spacefacey** [comment]
Not really Atlas but what about some Atlas V revamps?

**Comment by DaveJ576** [comment]
Is it possible to get proper versions of all of the Atlas ICBM warheads?
![atlas-ICBM](https://user-images.githubusercontent.com/94082725/166126573-e3405b60-18a9-4cc2-a12d-9f1e6db4fae6.jpg)

**Comment by zorg2044** [comment]
> Is it possible to get proper versions of all of the Atlas ICBM warheads

Not planning on doing more "reentry vehicles". We just have the Titan II one because that particular configuration looks very nice and the Peacekeeper one since it made sense as inspiration for a fairing.



> Here is another for consideration... I have it on reliable authority (Ed Kyle, spacelaunchreport.com) that all of the Atlas models with the stage and a half configuration (B through F, even to the Atlas 2AS) had only two "jettison tracks" on the sustainer section for the booster skirt, not four.

Yup that lines up with the reference diagrams I have. Appreciate the close up picture though.

**Comment by JovietUnion** [comment]
Does peacekeepers include minuteman III? And the decoys?

**Comment by CobaltWolf** [comment]
No, Peacekeeper is MX.

**Comment by CobaltWolf** [comment]
> Matt told me to do an issue for this for zorg or whoever gets around to the atlas revamp.
> 
> The current atlas tapered section is a straight angle, and is not filleted, like the real thing.
> 
> ![image](https://user-images.githubusercontent.com/17996283/182949818-e0c56b11-7def-4aac-8bc1-9fe2d2a56e02.png)
> 
> ![image](https://user-images.githubusercontent.com/17996283/182949864-c97a4681-185b-49c4-8eb9-ae5fe7c0216f.png)
> 
> I imagine the best way to implement this is like how it is done on SIV, where the filleted section is part of the tapered section.

#1278

**Comment by jehannes** [comment]
maybe a skirt with lr89 integrated for the early shared turbo pump variants?

**Comment by CobaltWolf** [comment]
@jehannes I don't think there's a need, since that would be functionally the same (in kerbal) as just placing the two separate engines on the skirt.

**Comment by zorg2044** [comment]
> On the topic of Atlas revamp, would that be possible to make a Star-63 (PAM-D2)? I'm asking because it was part of a peculiar Atlas variant, which stacked it with a Star-48A: https://web.archive.org/web/20220406014718/http://www.spacelaunchreport.com/atlas-k.jpg PAM-D2 actually flew on Commercial Titan 3 and on the Shuttle, however the Atlas-K proposal is probably the most interesting application for it.

Seems an easy ask. I'll put it on the list for later

![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/39182212/b34fe3ee-4854-4476-bcb8-b5a5b7229a68)

**Comment by JacobB094** [comment]
It should probably be noted that the motor had a white thermal blanket over it when it flew on the Shuttle:
![PAM-D2](https://upload.wikimedia.org/wikipedia/commons/b/b1/STS-61-B_SATCOM_Ku-2_deployment.jpg)

**Comment by JacobB094** [comment]
Since we now have a Delta-style paintjob for the Atlas tankage, I have a request that you'll find quite bizarre (and thus probably love it): a 3xLR-79 boattail, with 12 Delta-style SRB mounts, designed to attach below the _upper_ part of the Atlas V CCB.

The purpose of this part would be to recreate Delta 4000 from ETS, therefore completing the US rocket lineup from that AU. The upper tank from the CCB is about the right size for WBELT (same height as ELT, wide enough to comfortably fit 3 LR-79s and 12 boosters), so all it really needs is a nice, Delta-style boattail that would give the raceway a neat endcap and cover the engines. Additional configuration options are welcome, of course.

**Comment by zorg2044** [comment]
> Since we now have a Delta-style paintjob for the Atlas tankage, I have a request that you'll find quite bizarre (and thus probably love it): a 3xLR-79 boattail, with 12 Delta-style SRB mounts, designed to attach below the _upper_ part of the Atlas V CCB.
> 
> The purpose of this part would be to recreate Delta 4000 from ETS, therefore completing the US rocket lineup from that AU. The upper tank from the CCB is about the right size for WBELT (same height as ELT, wide enough to comfortably fit 3 LR-79s and 12 boosters), so all it really needs is a nice, Delta-style boattail that would give the raceway a neat endcap and cover the engines. The resulting rocket, tested with a stock engine plate, flies quite well. Additional configuration options are welcome, of course.

Hmm it's a thought, I'll keep it in mind if I have some texture space left. there was never any art for WBELT was there? its been a while since I read ETS. Was the diameter and tank lengths specified?

**Comment by JacobB094** [comment]
No, nothing but masses and engines. In fact, if made, the KSP rendition would be the first visual art of an ETS Delta 4000 and 5000. My work is pure scientific guesswork. This is probably the least developed launch vehicle in ETS, which is probably why nobody made anything for it back when Thor-Delta was being reworked. Quite frankly, it's also probably one of the least sensible bits from the AU, since the whole point of using Thor technology was that they could keep the tooling and so on.

I based my build on the following observations: 
1. WBELT needs to support 12 GEM-46s with enough space between them to allow a clean separation. That alone rules out a 3m (1.875m in KSP) core. A 4m core (2.5m KSP) allows for a little more clearance between boosters than on a Delta II Heavy. It also does not allow for more than 12 SRBs, either Castors or GEMs. So this checks out.
2. It's a tight fit, but 3xLR-79 can be crammed under a 2.5m tank in KSP with enough room for gimbaling and turbopump exhaust pipes. I would say that this further supports the 4m core diameter.
3. Propellant mass is about 67% of what Atlas V carries. Tank technology is essentially similar, so WBELT is probably not a common bulkhead stage. This works out to a stage that's about two thirds the length of Atlas V core, coincidently this is about the height of the ELT. The only conceivable reason to widen a stage instead of stretching it is keeping the rocket's height under control. The resulting vehicle, sans Centaur fairing, is the height of a Delta 3000 with the fairing. So about 22m (IRL) length for WBELT seems correct. I didn't run precise numbers, but a rough estimate checks out.
4. Now, the upper Atlas tank in BDB only looks right, it's actually shorter (due to the intertank with space for sep motors), but that's all right, the real thing would have had an intertank in the middle instead, so the propellant load checks out. It would likely have had separation motors, too. With three engines, it hits all the performance targets it's supposed to, including useful TWR in the boosterless configuration.

I wouldn't mind a dedicated tank for the WBELT, maybe using Thor textures, but the whole thing looks more like a deranged Atlas derivative than any sort of Delta, even if you do paint it blue. It does fly nicely, at least.

**Comment by JovietUnion** [comment]
So, would this meet the performance marks in JNSQ, or is this stock KSP
and/or OPM we're referring to?

**Comment by JacobB094** [comment]
My tests were in KSRSS 2.5x. In JNSQ, it would perform very similarly, except with extra margins for not having to deal with inclination.

**Comment by JacobB094** [comment]
Are suborbital payloads a possibility? Because

**Comment by zorg2044** [comment]
> Are suborbital payloads a possibility? Because there was this thing called project FIRE: https://en.wikipedia.org/wiki/Project_FIRE It involved an Antares-2 motor on top of the Atlas, as part of a "velocity package" that had some sort of system to orient it in space, but was spun up before motor firing. FIRE was an early reentry test, basically.

I'm not really interested in doing FIRE tbh

**Comment by JacobB094** [comment]
I have a small request regarding the large diameter CELV fairings. Could we have a round nose composite 4.25m fairing, possibly with the ability to use it on 3.125m bases (with a boattail section), too? It would be really nice to have a "modern" fairing in that size. While it was never a thing on Atlas, there was a 6.5m fairing proposed as a Delta IV Heavy expansion option, it could be based on that.

**Comment by zorg2044** [comment]
> Just to confirm, since I'm not seeing it on the roadmap, is the structural adapter for Atlas H fairing planned? It doesn't seem to be mentioned neither in the thread nor here.
> 
> Also, I would suggest renaming what is now called Atlas H extension tank to something generic, to avoid confusing people, since that part has nothing to do with Atlas H. It used the exact same lower stage as SLV-3D.

Is your BDB up to date? unless I missed something the only reference to Atlas H should be the 1.25m MSD short conical extension tank. This part should have been the structural adapter but was mistakenly added as a fuel tank. It was removed in a commit 3 weeks ago. https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/c26fad66edf2a415b735aed4f082d17ea4f7a073

The structural adapter with the same dimensions is planned to replace it.

**Comment by JacobB094** [comment]
OK, I didn't notice it being gone. FWIW, the tank itself could be useful, just not for Atlas H, just a generic short 1.25m extension.

**Comment by zorg2044** [comment]
It seemed a bit redundant to me given the other 1.25m adapter tank and potential for some confusion. I was wondering if anyone would even notice if it was gone. I could reactivate it if there was demand with a new generic name but well no one seemed to notice.

**Comment by zorg2044** [comment]
its just gonna be the MSD fairing with a wall segment. I dont intend to make it separately as its "close enough". The spacing of the bumps aren't worth the time, effort and texture space of a completely different almost identical fairing.

**Comment by JacobB094** [comment]
Since we're doing the Burner 2, any chance of getting Thor-Burner 2 hardware as well? Mostly the shroud and the Thor adapter. I think the shroud is the same nosecone that was used on Atlas-Burner 2, but the sidewalls (on Burner 2A) are short and red. The adapter is also white, and has a bit different shape.

Also, of note, Burner 1 also included CGTs in order to orient the Thor properly after engine burnout. I haven't been able to find out where they were (probably on the adapter), but would that be possible to add a small, radially attached thruster part with a small monoprop tank to replicate that?

**Comment by zorg2044** [comment]
> Since we're doing the Burner 2, any chance of getting Thor-Burner 2 hardware as well? Mostly the shroud and the Thor adapter. I think the shroud is the same nosecone that was used on Atlas-Burner 2, but the sidewalls (on Burner 2A) are short and red. The adapter is also white, and has a bit different shape.
> 
> Also, of note, Burner 1 also included CGTs in order to orient the Thor properly after engine burnout. I haven't been able to find out where they were (probably on the adapter), but would that be possible to add a small, radially attached thruster part with a small monoprop tank to replicate that?

Idea is to do Thor Burner 2 as well yeah when I get to it. Im not sure Burner 2 will make this update tho. 

Idk about Burner 1. I'll have a think about it together with the MSD guidance kit for which we have some rough pictures.

**Comment by JacobB094** [comment]
It would be nice if it could be crammed onto a single texture sheet with something like the MSD kit. To my knowledge, Burner 1 basically consisted of putting a Scout 4th stage, complete with the associated fairing, on top of a Thor. There was an earlier version which used an MG-18 (little difference from an Antares III, AFAIK) and a smaller fairing, also from Scout. Burner 1 was spin-stabilized, the CGTs were not part of a guidance kit like on Burner 2, but were mounted on the LV, like on the Scout's 3rd stage.

Also, would that be possible to get a "bottom rack" for mounting a Star-37 below Burner 2, to make Burner 2A? It'd probably be better to do that now rather than put it off for later, though it would probably also require making a Star-26 (which would go inside Burner 2, instead of the -37). At least, that's the impression of Burner 2A that I got from pictures.

**Comment by JacobB094** [comment]
I know it's a bit late, but would that be possible to make the bits around the XB-65 engine mount a toggle? The pipes and the lower part of the raceway, specifically.

Also, the pipe has a hole in the mesh on its upper surface. It's hidden in the intended configuration, but when kitbashing, it's not. Same problem on Atlas extension tanks (it's less conspicuous, but it's there) and the bottom of most other Atlas extension tanks.

**Comment by zorg2044** [comment]
> I know it's a bit late, but would that be possible to make the bits around the XB-65 engine mount a toggle? The pipes and the lower part of the raceway, specifically.

No this isn't possible due to baked AO on the texture. 

> Also, the pipe has a hole in the mesh on its upper surface. It's hidden in the intended configuration, but when kitbashing, it's not. Same problem on Atlas extension tanks (it's less conspicuous, but it's there) and the bottom of most other Atlas extension tanks.

I'll take a look at the pipes/raceways. Fixed some of them now.
